- docker/Dockerfile_stack
- docker/jenkins/build.sh
- docker/jenkins/docker-compose.yml
@mkstoyanov this is a work in progress.  Do not merge yet.
> Setup automated testing on Jenkins CI

- CMakeLists.txt
- DREAM/tasdreamExternalTests.cpp
- InterfaceMATLAB/tsgCoreTests.m
- Testing/fortester.f90
- Testing/multiBuildTest.sh
Fixed Clang-5.0 issue, some Fortran and MATLAB tests, bad performance with OpenBLAS and OMP_NUM_THREADS.
> Fix build test issues

- docker/Dockerfile_nvidia-cuda9.0-ubuntu16.04
- docker/jenkins/build.sh
> Add CUDA to automated testing

- InterfaceFortran/Makefile
- InterfaceMATLAB/tsgCoreTests.m
- InterfaceMATLAB/tsgEvaluate.m
- Makefile
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGrid.windows.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tasgridWrapper.hpp
- SparseGrids/tasgrid_main.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgCudaLinearAlgebra.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- Testing/multiBuildTest.sh
Added fail safety mechanism to ensure kernels are not called with wrong order. Added GPU acceleration for local polynomials and evaluateFast(). There is an option to force sparse backend acceleration algorithm. Cleaned Cuda warnings and function calls.
> Cuda updates

- Examples/example_sparse_grids.f90
- InterfaceFortran/tsgC2Fortran.cpp
- InterfacePython/TasmanianSG.in.py
- InterfacePython/TasmanianSG.py
- InterfacePython/TasmanianSG.windows.py
- README
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGrid.windows.hpp
- SparseGrids/WindowsMakeSG.bat
- SparseGrids/tsgIndexManipulator.cpp
- Testing/testTSG.in.py
- Testing/testTSG.py
- WindowsREADME.txt
- install
Done for the release, can wait a few days in case something comes up, but I'm done testing and developing (for this release that is).
> Release 51rw

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
* fixed bugs in the quadrature transforms for odd *gauss-* rules and *gauss-laguerre*
* merges many similar tests, now that the test are more robust there is no need for splitting the code for each rule
> Bugfix and test merge

- Config/CMakeLists.examples.txt
- SparseGrids/TasmanianSparseGrid.cpp
- install
* typos and code that should have been removed a few commits back
> Small fixes

- Config/AltBuildSystems/TasmanianSG.py
- Config/AltBuildSystems/TasmanianSG.windows.py
- Config/AltBuildSystems/testTSG.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/testTSG.in.py
- SparseGrids/TasmanianSparseGrid.cpp
This branch implements a Python wrapper for the Fourier basis. I've tested this out in a Jupyter notebook.
> Python interface for Fourier

- InterfaceMATLAB/tsgMakeLocalPolynomial.m
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tasgridTestFunctions.cpp
- SparseGrids/tasgridTestFunctions.hpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
* added new rule: `rule_localpb` or `localp-boundary`
* the new rule focuses points on the boundary of the domain
* added tests and acceleration
> New local rule

- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridSequence.cpp
* added magma dense matrix-matrix for batched evaluations of sequence grids
* added magma dense matrix-vector for fast evaluations of global and sequence grids
> More magma integration

- SparseGrids/tsgCoreOneDimensional.cpp
Should have had this at the beginning; did not notice until now
> added Fourier rule to getIExact and getQExact

- SparseGrids/tasgridExternalTests.cpp
* *Note* this is a basic benchmark, not the full one used for tuning
* removed the surplus section
* added magma section
* added fast evaluations
> updated the benchmark test (low priority)

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgLinearSolvers.cpp
Valgrind on Titanmath caught some memory leaks. No complaints from valgrind after these changes.
> fix memory leaks

- SparseGrids/tasgridExternalTests.cpp
> memory leak

- DREAM/tasdreamExternalTests.cpp
* note that the bug is in the tester executable and not the library
> fixed memory leak in the dream tests

- Testing/multiBuildTest.sh
* Tasmanian now has docker based nightly test system coveting many versions of gcc, clang, python, etc.
* As a result, the quick and dirty multi-tests can be simplified to save time
> simplified multi-tests, this will be caught in nightly builds

- DREAM/tasdreamExternalTests.cpp
* another missing delete from testing
> somehow valgrind missed that one

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
* external API has getPoints() and getWeights() using `std::vector`
* the `ExternalTester::getError()` is set to use the vector API
> Add std vector interface for getPoints() and getWeights()

- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
* replace active weights array with `std::vector`
> replaced active weights by std vectors

- CHANGELOG.md
> updated the changelog

- DREAM/tasdreamExternalTests.cpp
* valgrind is silent after this change
> missing explicit delete in dream testing

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgCudaMacros.hpp
* added external API calls based on `std::vector`
* the new API wraps around the old calls with `.data()`, but add more functionality
* if needed, the output vectors are automatically resized
* error checking can be added in the future to ensure that input vectors have the right `.size()`
* evaluate sparse basis requires some considerable thinking
> Vector external api

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
* converted the domain transforms to vectors
> converted domain transforms to vectors

- Config/AltBuildSystems/TasmanianSG.py
- Config/AltBuildSystems/TasmanianSG.windows.py
* the alternative build system is updated with new Fourier coefficients
> updated the alternative build systems

- Config/AltBuildSystems/testTSG.py
- InterfaceFortran/fortester.f90
- InterfaceFortran/tsgC2Fortran.cpp
* removed trailing white spaces
* updated the alt build tests
> Trailing spaces

- CHANGELOG.md
- Config/AltBuildSystems/HeaderConvert.py
- Config/AltBuildSystems/TasmanianSG.py
- Config/AltBuildSystems/TasmanianSG.windows.py
- InterfaceFortran/TasmanianSG.f90
- InterfaceFortran/tsgC2Fortran.cpp
- InterfacePython/TasmanianSG.in.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridWrapper.cpp
* removed the `logstream` mechanics, errors in C++ are handled with exceptions
* the `read()` function is now void (all good unless `std::runtime_error` is thrown)
* the interfaces still use boolean true/false logic
> Api change logs

- DREAM/TasmanianDREAM.cpp
- DREAM/TasmanianDREAM.hpp
- DREAM/tasdreamBenchmark.cpp
* removed the `logstream` in the DREAM classes
* upgraded the error handling to exceptions
> Update dream error api

- DREAM/TasmanianDREAM.cpp
- DREAM/TasmanianDREAM.hpp
- DREAM/tasdreamBenchmark.hpp
- DREAM/tdrCorePDF.cpp
- DREAM/tdrCorePDF.hpp
- DREAM/tdrEnumerates.hpp
- InterfaceFortran/tsgC2Fortran.cpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridWrapper.hpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgSequenceOptimizer.cpp
* various minor bug fixes and style format
* removed debug statements and obsolete code
> Misc fixes

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridUnitTests.cpp
* fix get points potential overflow
* a few vector api fixes
> Getpoints overflow

- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* small fixes in the wavelet class
> Small performance fixes

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridUnitTests.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* added vector API for the refinement functions
* added sanity check for inputs with appropriate exceptions
> Vector refine api

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
* updated the internal API for anisotropic weights and level limits, everything is `vector` based
> Vectors internal api

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridUnitTests.cpp
* small fixes caught by the nightly builds
> Daily fixes

- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
* added vectors in global grid surpluses
* removed the possibility of size overflow
> Vectors surplus

- SparseGrids/CMakeLists.txt
- SparseGrids/gridtest_main.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridUnitTests.hpp
* expanded functionality of `gridtest`
* added API tests for vector and array variants of functions
> Gridtest updates

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* added Fast Fourier Transform algorithm for arbitrary dimension and Radix-3
* reversed the order of for-loops in the Fourier grid (massive speedup)
* enabled acceleration tests with many outputs, since the grids are **much** faster now
* the old code is still kept, blocked by a constant if-statement, for testing purposes
> Fast fourier transform

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* remove danger of overflow in all by sparse and cuda functions
* switch internal data structures to vectors (in most cases)
* improved overall performance
> Overflow in localp

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgHiddenExternals.hpp
* BLAS acceleration for Fourier grids in `evaluateFast()` and `evaluateBatch()`
> Fourier blas acceleration

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgGridLocalPolynomial.cpp
* updated the dynamic memory in sparse matrix build
* updated the GPU domain transform
> Cuda vectors kernels

- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
* GPU acceleration using cuBlas and MAGMA for Fourier grids
> Gpu acceleration fourier

- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
- SparseGrids/tsgOneDimensionalWrapper.cpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
* update the `OneDimensionaWrapper` from array to vector format
* updated the non-nested point generation
> Vectors in wrapper

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
* evaluations of Sequence basis functions using CUDA
* linked to CUDA and MAGMA acceleration
* added tests
> Cuda sequence evals

- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* fixed a bug with array sizes
* vectors in Sparse Matrix and GMRES solver
> Vector sparse linalg

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
* vectors and no overflow in internal API for linear and conformal transforms
> More internal vector api

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
* using vector data structure and removed the possibility of overflow in Fourier grids
> Vectors fourier grids

- SparseGrids/CMakeLists.txt
- SparseGrids/Makefile
- SparseGrids/gridtest_main.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestInterfaceC.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridUnitTests.hpp
* add testing to the C interface and some of the more obscure use cases
> Expand testing

- InterfaceFortran/tsgC2Fortran.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgrid_main.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgHardCodedTabulatedRules.cpp
- SparseGrids/tsgHardCodedTabulatedRules.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* small fixes to the internal API
* remove deprecated code, updating the internal API created obsolete code
* added some additional coverage
* tested consistent string/int/enumerate conversions for the interfaces
> Small updates internal api

- CMakeLists.txt
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
* figured out how to properly set the flags under windows with cmake
> Windows flags

- CHANGELOG.md
- CMakeLists.txt
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- DREAM/CMakeLists.txt
- DREAM/Examples/example_dream.cpp
- DREAM/tasdreamExternalTests.cpp
- DREAM/tasdreamExternalTests.hpp
- InterfacePython/testTSG.in.py
- README.md
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridUnitTests.cpp
- WindowsMake.bat
- WindowsREADME.txt
* fixed windows support for CUDA, Python, DREAM (test seed), shared only libraries, Release/Debug paths and flags, several small bugs and warning fixes
* Python getGPUName() fails under windows, needs further investigation
> Windows pythons fixes

- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgIndexManipulator.hpp
* added more explicit parentheses to some logical branches, fixes possible compiler bug
> Possible bug fix

- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
* fix bug when BLAS wasn't ON after using RECOMMENDED and BLAS_LIBRARIES
> set enable blas on, when using recommended and custom libs

- DREAM/Examples/example_dream.cpp
- DREAM/TasmanianDREAM.cpp
- DREAM/TasmanianDREAM.hpp
- DREAM/tasdreamTestPDFs.cpp
- DREAM/tasdreamTestPDFs.hpp
* fix vector calls, made all by reference as opposed value
> fix vector api, calls by reference

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
* one more place with vectors used by value
* removed default (mostly unused) from internal API
> Vectors by reference

- DREAM/TasmanianDREAM.cpp
- DREAM/TasmanianDREAM.hpp
- DREAM/tasdreamTestPDFs.cpp
- DREAM/tasdreamTestPDFs.hpp
* DREAM classes automatically find the implemented virtual interface (vectors or arrays)
> remove API version, automatically check vectors vs arrays

- DREAM/Examples/example_dream.cpp
- DREAM/TasmanianDREAM.cpp
- DREAM/tasdreamExternalTests.cpp
- DREAM/tasdreamTestPDFs.cpp
- DREAM/tdrCorePDF.cpp
- DREAM/tdrCorePDF.hpp
- SparseGrids/TasmanianSparseGrid.cpp
* fixed regression bug in DREAM with the new vector API
* outputs vectors are now always resized consistently in DREAM and SG
> Dream vector fixes

- CMakeLists.txt
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- InterfacePython/testTSG.in.py
* set the repo ready for the release
> Release candidate

- Config/AltBuildSystems/TasmanianSG.py
- Config/AltBuildSystems/TasmanianSG.windows.py
- Config/AltBuildSystems/testTSG.py
- DREAM/tasdreamExternalTests.cpp
- InterfacePython/TasmanianSG.in.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tasgrid_main.cpp
* fixed some last minute bugs
* silenced development debug I/O in some tests
* updated some documentation
> Final small fixes

- Config/AltBuildSystems/TasmanianConfig.hpp
- Config/AltBuildSystems/TasmanianSG.py
- InterfacePython/CMakeLists.txt
* version bump for the GNU Make build engine
* removed Windows Python test file for batch Windows build system
> Gnu make version bump

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* convert localp, global, wavelet, and Fourier grids to using storage sets with RAII memory management
> Raii storage sets

- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
- SparseGrids/tsgOneDimensionalWrapper.cpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
* convert wrappers, custom rule, and matrix objects to RAII memory
> Raii aux classes

- SparseGrids/tsgGridCore.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
* converted local polynomial and wavelet grids to RAII memory management
* converted the multiple local polynomial rules to a unique pointer
> Raii localp wavelet grids

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* converted global and fourier grids to RAII memory management
> Raii global and fourier grids

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.hpp
* convert the 5 grid pointers in `TasmanianSparseGrid` to a single `unique_pntr`
> Main class unique pointer

- CMakeLists.txt
- Doxygen/CMakeLists.txt
- Doxygen/DoxygenMainPage.hpp
- SparseGrids/tsgIndexManipulator.hpp
* enable Doxygen documentation (very sparse at the moment)
> Include doxygen

- Doxygen/CMakeLists.txt
- SparseGrids/tsgIndexSets.hpp
* added documentation to `tsgIndexSets.hpp`
> Added documentation for the set data-structures

- CHANGELOG.md
- Doxygen/CMakeLists.txt
- Doxygen/Installation.md
- Doxygen/tasmanian.css
- README.md
- SparseGrids/tsgIndexManipulator.hpp
* updated the installation instructions and Doxygen relative paths
* updated the changelog and fixed some doc problems
> Extra docs

- Doxygen/CMakeLists.txt
- Doxygen/tasmanian.css
- SparseGrids/tsgEnumerates.hpp
* document the enumerate types
> Documented the internal and external enumerated types.

- DREAM/tasdreamExternalTests.cpp
- DREAM/tsgDreamSample.hpp
- DREAM/tsgDreamSampleGrid.hpp
- DREAM/tsgDreamSamplePosterior.hpp
- DREAM/tsgDreamState.cpp
- DREAM/tsgDreamState.hpp
* fixed couple of bugs (domain not properly set in one overload and error message had wrong test)
* added counter for the acceptance rate, with testing and regression check
* reformatted some code (used the wrong editor earlier)
> Small dream features

- Config/CMakeLists.examples.txt
- DREAM/CMakeLists.txt
- DREAM/Examples/example_dream.cpp
- DREAM/Examples/example_dream_01.cpp
- DREAM/Examples/example_dream_02.cpp
- DREAM/Examples/example_dream_03.cpp
- Doxygen/CMakeLists.txt
* added DREAM example 3
* split the examples into separate Doxygen groups to improve readability
> More dream examples

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
Replace some old C++98 code with C++11 algorithms.
> Algorithm updates

- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaMacros.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
- SparseGrids/tsgSequenceOptimizer.hpp
* cleaned some redundant dependencies and code that generates (sometimes erroneous) warnings and errors
* cleaned the old algorithm for high order localp evaluations
> Acc dependence cleanup

- Doxygen/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgHiddenExternals.hpp
* simplified/unified blas API similar to CUDA
> Blas update

- SparseGrids/Makefile
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
* fixed a few api error and expanded testing to prevent regression
> More testing

- SparseGrids/tsgGridCore.cpp
- SparseGrids/tsgGridCore.hpp
* replaced an n-squared algorithm with equivalent n log(n) algorithm
* the n-squared algorithm is seldom used with very large n, but async sampling may have to call it often
> replaced an n-squared algorithm with n log-n

- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
* simplified the tree/graph manipulations, needed to recompute surpluses in dynamic construction mode
> Simplify localp tree algs

- Config/AltBuildSystems/TasmanianSG.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/testRefinement.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgIOHelpers.hpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* added dynamic construction for local polynomial grids
> Dynamic localp construction

- Doxygen/CMakeLists.txt
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgUtils.hpp
* added an Utils internal header with templates that reduce dangling pointers
* reduced uninitialized uses of the Data2D template
> Utils templates

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.hpp
* added cuda acceleration for computing hierarchical coefficients for localp grid
* updated the internal api to allow acceleration for other grids later
* added acceleration testing
> Cuda load values

- Config/CMakeIncludes/FindTasmanianCudaMathLibs.cmake
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Config/TasmanianConfig.in.cmake
- SparseGrids/CMakeLists.txt
* cuda is enabled as a cmake language
* added all the required hacks to avoid extraneous dependencies and feature regressions
> cuda enables as a cmake language

- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
* better load balancing on the CPU cores when computing surplus coefficients
* particularly effective for highly anisotropic and localized grids
> Load balance surpluses

- Testing/test_post_install.in.sh
* propagate the omp number of threads to the post-install test
> propagate the omp number of threads to the post-install test

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
* added move constructor to TasmanianSparseGrid class
* add move and assignment operator=
> Movable main class

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* local polynomial, Fourier, and sequence grid can perform evaluations with arrays on the cuda device
* added testing, error checking and the api backbone for other grid
> Gpu to gpu evals

- DREAM/tasdreamExternalTests.cpp
- DREAM/tasdreamExternalTests.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- docker/jenkins/build.sh
* switched sparse grid testing to implementation independent random number generator
* updated the dream random seed selection
> Update random engine

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* fixed performance bug when dealing with many outputs and wavelet grids
* improved performance in the wavelet rule class
* enabled cuda-mixed acceleration for wavelet grids
> Speed up wavelets

- SparseGrids/Makefile
* added the split C interface from the gnu make system
> fix the gnu make engine for the new C interface

- Config/CMakeLists.examples.txt
- Makefile
- SparseGrids/CMakeLists.txt
- Testing/test_post_install.in.sh
* disable the sparse grids example until small api and examples update
> Disable sg examples until update

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchEvaluate.hpp
- SparseGrids/Benchmarks/bench_main.cpp
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/gridtest_main.cpp
- SparseGrids/tasgridCLICommon.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridUnitTests.hpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tasgridWrapper.hpp
- SparseGrids/tasgrid_main.cpp
* create a common collection of cli tools, process args, check for "help", etc.
* replace with c-style strings by c++ std::string
* switch the cli wrapper api to containers and raii memory
> Common cli tools

- DREAM/Examples/example_dream_02.cpp
- DREAM/Examples/example_dream_03.cpp
- DREAM/tasdreamExternalTests.cpp
- DREAM/tasdreamExternalTests.hpp
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestFunctions.cpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgLinearSolvers.cpp
* replaced macros by `constexpr` variables
* added `constexpr double tsg_pi` to replace `M_PI` and eventually remove the dependence on `math.h`
> Replace macros by constexpr

- DREAM/CMakeLists.txt
- DREAM/tsgDreamSampleGrid.hpp
- DREAM/tsgDreamSamplePosterior.hpp
- SparseGrids/tasgridCLICommon.hpp
* fixed windows build system: missing headers, updated test names, capture lambdas by reference
> Windows fixes

- DREAM/TasmanianDREAM.hpp
- DREAM/tsgDreamSampleGrid.hpp
- DREAM/tsgDreamSamplePosteriorGrid.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgRuleWavelet.cpp
* removed all c-style macros and replaced with c++ code
> Remove macros

- DREAM/CMakeLists.txt
- SparseGrids/CMakeLists.txt
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgIndexManipulator.hpp
* removed some obsolete windows workarounds
* fixed some warnings
> Windows updates

- InterfaceFortran/tsgC2Fortran.cpp
* updated the C++ side of the Fortran interface to STL containers and algorithms
> containers in the c++ side of the fortran interface

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchEvaluate.hpp
- SparseGrids/Benchmarks/benchLoadNeeded.hpp
- SparseGrids/Benchmarks/benchMakeGrid.hpp
- SparseGrids/Benchmarks/bench_main.cpp
- SparseGrids/CMakeLists.txt
* added benchmarks for make grid and load needed points
* improved the templates for parsing long lists of input parameters
> More benchmarks

- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.hpp
* make localp grid is now parallelized in the most heavy operation of get-slot
> Parallel make localp

- SparseGrids/Makefile
* add the new source files to the GNU make system
> fixed the gnu make system

- SparseGrids/TasmanianSparseGrid.cpp
* improved the error message when given incorrect file-name
> better error messages on missing files

- Config/CMakeLists.examples.txt
* fix cmake version requirement in examples
> fix cmake version

- docker/jenkins/build.sh
* restore parallel ctest and less verbose console output
> restore parallel ctest

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
small patch: add case for Fourier grids
> getPointsIndexes() for Fourier grids

- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
* removing points by surplus does not recompute the surpluses
* document that the refine and update procedures cannot be used anymore
> Improvements

- Doxygen/CMakeLists.txt
- Doxygen/footer.html
- Doxygen/tasmanian.css
* removed double scrollbars on the right-side
* adjust the font-sizes by a bit
> Adjust docs

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
This pull request adds the functions and data structures that will be used in the refinement strategy. All functions are currently empty.
> Refinement strategy

- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
Refinement variables and file I/O
> add variables for the refinement to header and file I/O

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgIndexManipulator.hpp
This branch implements anisotropic refinement for Fourier grids. Tests added to `tasgridExternalTests.cpp`.
> Fourier anisotropic refinement

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchFFT.hpp
- SparseGrids/Benchmarks/benchInterpolationWeights.hpp
- SparseGrids/Benchmarks/bench_main.cpp
This branch adds benchmarks for `getInterpolationWeights()`. It is a continuation of Pull Request #301  (branch renamed for clarity).
> Interpolation weights benchmarks

- SparseGrids/tsgGridFourier.cpp
This branch implements a new algorithm for computing the interpolation weights for Fourier grids. The mathematical details are in the comment lines of `GridFourier::getInterpolationWeights()`. The benchmarks indicate that this new algorithm results in a speedup of ~5x.
> New algorithm for interpolation weights in Fourier grids

- CHANGELOG.md
- CMakeLists.txt
- Config/CMakeIncludes/master_targets.cmake
- Config/CMakeLists.examples.txt
- Config/TasmanianConfig.in.cmake
- Testing/tasmanian_version.cpp
* add Tasmanian CMake master targets
> Cmake master target

- CHANGELOG.md
- Config/CMakeIncludes/master_targets.cmake
- DREAM/CMakeLists.txt
- DREAM/Examples/example_dream_04.cpp
* few small adjustments related to recent changes
> Random adjustments

- Addons/CMakeLists.txt
- Addons/testMPI.cpp
- Addons/testMPI.hpp
- Addons/tsgAddonsCommon.hpp
- Addons/tsgMPIScatterGrid.hpp
- Doxygen/CMakeLists.txt
* added methods to send-recv a grid across MPI comm
> Send/Recv across MPI comm

- Addons/testMPI.cpp
- Addons/testMPI.hpp
- Addons/tsgMPIScatterGrid.hpp
* add MPI Bcast method for sparse grids
* improved testing and documentation
> Grid bcast

- Addons/tsgMPIScatterGrid.hpp
- CHANGELOG.md
- Config/CMakeIncludes/master_targets.cmake
- Config/TasmanianConfig.in.cmake
- Doxygen/Installation.md
* master imported targets are globally visible
* fixes in documentaion
> Small improvements

- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgIndexManipulator.hpp
* improving the backend for handling multiple constructed points (will propagate to top interface)
> Batch add points

- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgHierarchyManipulator.hpp
* batch construction backend for local polynomial grids
> Batch constructed points

- Config/AltBuildSystems/TasmanianSG.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/testRefinement.py
- SparseGrids/TasmanianSparseGridWrapC.cpp
* batch loading of constructed points added to the Python interface
> Python multipoint construction

- Addons/CMakeLists.txt
- Addons/testAddons.cpp
- Addons/testConstructSurrogate.hpp
- Addons/tsgAddonsCommon.hpp
- Addons/tsgCandidateManager.hpp
- Addons/tsgConstructSurrogate.hpp
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Doxygen/CMakeLists.txt
- InterfacePython/sandbox.py
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
* added templates to automatically sample from a model defined by a lambda
* sampling can be done sequentially or in parallel using c++ threads (does not require OpenMP)
> Automated construction

- Config/CMakeLists.examples.txt
- Doxygen/CMakeLists.txt
- Makefile
- SparseGrids/CMakeLists.txt
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_01.cpp
- SparseGrids/Examples/example_sparse_grids_02.cpp
- SparseGrids/Examples/example_sparse_grids_03.cpp
- Testing/test_post_install.in.sh
* re-enabled the first 3 sparse grids examples
* updated the API, features and documentation
> Examples sq

- Config/AltBuildSystems/TasmanianSG.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/testAcceleration.py
- InterfacePython/testExceptions.py
- InterfacePython/testRefinement.py
- InterfacePython/testUnstructuredData.py
* fixed some missing python tests with Fourier and dynamic construction
> Fix python omissions

- InterfacePython/testRefinement.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridWavelet.cpp
* updated copy-grid procedures to take advantage of containers copy assignment
* removes redundant computations and assumptions regarding the internal state
* added testing for copy of construction data
> Copy dynamic construction data

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgridUnitTests.hpp
- SparseGrids/tsgCoreOneDimensional.cpp
* replaced switch statements with lambdas when checking exceptions
* no need to count/order the index of the case and statements are isolated
> improved cpp exceptions checks

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgUtils.hpp
* template that makes a copy of small arrays into vectors
> template to copy small arrays into vectors

- Config/AltBuildSystems/TasmanianSG.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/testBasicIO.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexSets.hpp
* capability to copy a grid but with only a portion of the outputs
> capability to copy a grid but with only portion of the outputs

- Makefile
* addon tests included in gnu make
> added addon tests to gnu make

- Config/CMakeIncludes/exports.cmake
- Config/CMakeLists.examples.txt
- Config/TasmanianConfig.in.cmake
* added components to the Tasmanian package config corresponding to all options
* added MATLAB path to the config, in case needed
> Cmake components

- Addons/testMPI.cpp
- Addons/testMPI.hpp
- Addons/tsgMPIScatterGrid.hpp
- SparseGrids/TasmanianSparseGrid.hpp
* added template to scatter a grid across an MPI comm
> Scatter grid

- Addons/testConstructSurrogate.hpp
- Addons/tsgCandidateManager.hpp
- Addons/tsgConstructSurrogate.hpp
* samples in construction can be processed by the lambda in batches
> Batch sampling

- Addons/tsgConstructSurrogate.hpp
* added ability to feed initial guess to the construction lambda
> added ability to feed initial guess to the construction lambda

- Addons/CMakeLists.txt
- Addons/testConstructSurrogate.hpp
- Addons/testMPI.cpp
- Addons/testMPI.hpp
- Addons/tsgAddonsCommon.hpp
- Addons/tsgConstructSurrogate.hpp
- Addons/tsgMPIConstructGrid.hpp
- Doxygen/CMakeLists.txt
* fixed the old thread sampling and added mpi sampling
* added documentation
> mpi construction

- Config/CMakeIncludes/CMakeLists.txt
- Doxygen/CMakeLists.txt
- Doxygen/InterfacePython.md
- InterfacePython/CMakeLists.txt
- InterfacePython/Tasmanian.py
- InterfacePython/example_sparse_grids.in.py
- InterfacePython/testExceptions.py
- Makefile
- Testing/test_post_install.in.sh
* added a python master module and associated documentation
> Python master module

- CHANGELOG.md
- README.md
* removed the obsolete manual and updated the readme and changelog files
> Remove pdf manual

- Addons/testConstructSurrogate.hpp
- Addons/testMPI.cpp
- Addons/testMPI.hpp
- Addons/tsgCandidateManager.hpp
- Addons/tsgConstructSurrogate.hpp
- Addons/tsgMPIConstructGrid.hpp
- Addons/tsgMPIScatterGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgHierarchyManipulator.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- docker/jenkins/build.sh
* fixed several hard to reproduce segfault bugs in points manager
* using single thread per job for parallel sampling (lower overhead)
* fixed bugs in localp grids and construction with multiple parents
* adjusted parameters and tolerances for many tests
> bugs everywhere

- Addons/CMakeLists.txt
- Addons/testConstructSurrogate.hpp
- Addons/tsgMPIConstructGrid.hpp
- InterfacePython/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.hpp
* added non-blocking mpi, puts the thread to sleep while the model is computing
> Non blocking mpi

- DREAM/tasdreamExternalTests.cpp
- DREAM/tsgDreamLikelyGaussian.cpp
- DREAM/tsgDreamLikelyGaussian.hpp
* added anisotropic diagonal Gaussian likelihood to DREAM
> Diagonal gauss likelihood

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestFunctions.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
* added dynamic construction capabilities to Fourier grids
* fixed bugs with the custom domain transform (affected all grids)
> Fourier dynamic construction

- CHANGELOG.md
- InterfaceFortran/Examples/example_sparse_grids.f90
- InterfaceFortran/TasmanianSG.f90
- InterfaceFortran/fortester.f90
- InterfaceFortran/tsgC2Fortran.cpp
* updated the Fortran interface to remove the global state
> Fortran pointers

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.txt
- Doxygen/CMakeLists.txt
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_01.cpp
- SparseGrids/Examples/example_sparse_grids_02.cpp
- SparseGrids/Examples/example_sparse_grids_03.cpp
- SparseGrids/Examples/example_sparse_grids_04.cpp
* added sparse grids example 4
> Sg examples

- InterfaceFortran/CMakeLists.txt
- InterfaceFortran/TasmanianSG.f90
- InterfaceFortran/mpitester.f90
- InterfaceFortran/tsgC2Fortran.cpp
* added bindings for the MPI methods to Fortran
> Mpi fortran

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.txt
- Doxygen/CMakeLists.txt
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_05.cpp
> Sg example5

- Addons/tsgConstructSurrogate.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
- SparseGrids/tsgUtils.hpp
* adjustments for strange compilers
* pgi doesn't like vector of atomics
* msvc gives conversion warnings even under static_cast
> Other compatibility

- InterfaceFortran/TasmanianSG.f90
- InterfaceMATLAB/tsgRefineSurplus.m
- InterfacePython/TasmanianSG.in.py
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgHierarchyManipulator.cpp
- SparseGrids/tsgHierarchyManipulator.hpp
- SparseGrids/tsgIOHelpers.hpp
* added localp refinement that keeps all parents
* dynamic construction any parents refinement weights parents ahead of children
> Stable localp refinement

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.txt
- Doxygen/CMakeLists.txt
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_06.cpp
* added sparse grids example 6
> added example 6

- InterfacePython/TasmanianSG.in.py
- InterfacePython/testUnstructuredData.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* added functionality to return the integrals of hierarchical basis functions
* added functionality to return the loaded value
* both added to c c++ and py
> Points and integrals

- Addons/CMakeLists.txt
- Addons/Makefile
- Addons/tsgCLoadNeededValues.cpp
- DREAM/Makefile
- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianAddons.in.py
- InterfacePython/TasmanianSG.in.py
- InterfacePython/example_sparse_grids_05.py
- Makefile
* here is a working example of the python callback using `numpy.ndarrays` and multi-threading
* the most important files are `loadNeededPoints.cpp`, `TasmanianAddons.in.py` and the example 5
> Python addons

- Addons/CMakeLists.txt
- Addons/Makefile
- Addons/tsgCConstructSurrogate.cpp
- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianAddons.py
- InterfacePython/example_sparse_grids_06.py
- InterfacePython/testAddons.py
- InterfacePython/testTSG.py
* added py bindings to the construction algorithm templates
* added tests for the addon capabilities
> Pyconstruct grid

- InterfacePython/CMakeLists.txt
> missing correction to the windows build

- Addons/CMakeLists.txt
- DREAM/CMakeLists.txt
- SparseGrids/CMakeLists.txt
* added rpath to libraries so they can find each other after post-install
> set the rpath to libraries

- DREAM/Examples/example_dream_01.cpp
- InterfacePython/CMakeLists.txt
- InterfacePython/example_dream.in.py
- InterfacePython/example_dream_01.py
> Pydream example

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridWavelet.cpp
* fixed the stable refinement in the local polynomial case
* added stable refinement to the wavelet grids
> Updated stable refinement

- CHANGELOG.md
- InterfacePython/TasmanianSG.py
- InterfacePython/testDream.py
- InterfacePython/testMakeUpdate.py
- SparseGrids/CMakeLists.txt
- install
* added factory sparse grid methods to python
* fixed typos and updated some documentation
* adjusted some tests to increase coverage
> Small updates

- Addons/tsgCConstructSurrogate.cpp
- Addons/tsgConstructSurrogate.hpp
- InterfacePython/testAddons.py
* removed incompatible input for the construction grid method
* removed the finish-construction call, since it can lead to loss of computed data
> Construction fixes

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.txt
- Doxygen/CMakeLists.txt
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_07.cpp
> Sg example7

- DREAM/tsgDreamEnumerates.hpp
- InterfacePython/TasmanianDreamSampler.py
* fix missing and incorrect internal documentation
> Fix dream docs

- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianDreamSampler.py
- InterfacePython/example_dream.in.py
- InterfacePython/example_dream_02.py
> Pydream example2

- InterfaceFortran/tsgC2Fortran.cpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridUnitTests.cpp
* adjust the conformal api
* remove redundant checks for surplus refinement
> Small api updates

- InterfacePython/CMakeLists.txt
- InterfacePython/example_dream_03.py
* added python dream example 3
> Pydream example 03

- InterfacePython/CMakeLists.txt
- InterfacePython/example_dream_03.py
- InterfacePython/example_dream_04.py
* added python dream example 4
> Pydream example4

- InterfacePython/CMakeLists.txt
- InterfacePython/example_dream_05.py
* added python dream example 5
> Pydream example5

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* added pure cuda acceleration for wavelet grids
> Cuda wavelets

- CHANGELOG.md
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
- SparseGrids/tsgUtils.hpp
* added CUDA acceleration mode for global grids
> Cuda global

- Addons/tsgConstructSurrogate.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* added construction procedure for wavelet grids
* tested for correctness but not optimized for speed
> wavelet construction

- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- Config/CMakeIncludes/setup_message.cmake
- Makefile
* set to release candidate and establish a *feature freeze*
> set release candidate

- Doxygen/InterfacePython.md
- InterfacePython/TasmanianDreamSampler.py
* updated the documentation for the pydream module
> Python docs

- Addons/testMPIDream.hpp
- Addons/tsgMPISampleDream.hpp
- DREAM/Examples/example_dream_03.cpp
- DREAM/Examples/example_dream_04.cpp
- DREAM/Examples/example_dream_05.cpp
- DREAM/tasdreamExternalTests.cpp
- DREAM/tsgDreamSample.hpp
- InterfacePython/TasmanianDreamSampler.py
- InterfacePython/example_dream_04.py
- InterfacePython/testDream.py
* fix api inconsistencies found during documentation
> Small adjustments

- InterfacePython/CMakeLists.txt
- InterfacePython/example_sparse_grids.in.py
- InterfacePython/example_sparse_grids_01.py
- InterfacePython/example_sparse_grids_02.py
- InterfacePython/example_sparse_grids_03.py
- InterfacePython/example_sparse_grids_04.py
* added python sparse grid examples 1 - 4
> Pyexamples

- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Config/TasmanianConfig.in.hpp
- InterfacePython/CMakeLists.txt
* multiple fixes on the windows build system (some affect unix as well)
> Build sys fixes

- Config/AltBuildSystems/tsgGetPaths.m
- Config/CMakeIncludes/CMakeLists.txt
- Config/TasmanianENVsetup.in.sh
- InterfaceMATLAB/CMakeLists.txt
- InterfaceMATLAB/tsgCleanTempFiles.m
- InterfaceMATLAB/tsgCopyGrid.m
- InterfaceMATLAB/tsgCoreTests.m
- InterfaceMATLAB/tsgDeleteGrid.m
- InterfaceMATLAB/tsgEvaluateHierarchy.m
- InterfaceMATLAB/tsgGetPaths.build.m
- InterfaceMATLAB/tsgGetPaths.install.m
- InterfaceMATLAB/tsgReadMatrix.m
- InterfaceMATLAB/tsgReloadGrid.m
- InterfaceMATLAB/tsgWriteCustomRuleFile.m
- InterfaceMATLAB/tsgWriteMatrix.m
- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianConfig.in.py
- Makefile
- Testing/test_post_install.in.sh
- install
* fixed install path bugs, problems with spaces and cleaning the source dir
* fixed the Python transitive lib-dependencies on Windows
* fixed several small typo-like of bugs
> More fixes

- Addons/tsgConstructSurrogate.hpp
- Addons/tsgMPIConstructGrid.hpp
- SparseGrids/tsgEnumerates.hpp
* added more references and fixed some documentation alignment
> More docs updates

- Addons/tsgMPIConstructGrid.hpp
- Addons/tsgMPISampleDream.hpp
- DREAM/tsgDreamSample.hpp
* added alias types to the dream lambdas which improves the alignment in the docs
* added cleaner documentation to all the alias types
> better dream alignment

- Addons/testConstructSurrogate.hpp
- CMakeLists.txt
- Config/AltBuildSystems/HeaderConvert.py
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Doxygen/Installation.md
- Doxygen/InterfacePython.md
- SparseGrids/TasmanianSparseGrid.h
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgrid_main.cpp
- SparseGrids/tsgEnumerates.hpp
* final adjustments, building the automatically generated C header
* remove the release candidate notes from CMake
* made a pass-though to spellcheck and adjust the documentation
> Final updates

- Doxygen/Installation.md
- Doxygen/InterfacePython.md
- Doxygen/tasmanian.css
* aligned the example code snippets to 100 characters
* added a list of known issues on release time
> Final alignment

- Addons/Makefile
- DREAM/Makefile
- InterfaceFortran/Makefile
- Makefile
- SparseGrids/Makefile
* fixed rpath and python in gnu make
> fixed rpath and python in gnu make

- Addons/Makefile
- DREAM/Makefile
- SparseGrids/Makefile
> fix rpaths

- .gitattributes
* ignore the jenkins file on release
> ignore jenkins on release

- Addons/CMakeLists.txt
- CHANGELOG.md
- CMakeLists.txt
- Config/AltBuildSystems/Makefile.in
- Config/AltBuildSystems/TasmanianConfig.hpp
- Config/CMakeIncludes/CMakeLists.txt
- Config/TasmanianConfig.in.hpp
- DREAM/CMakeLists.txt
- Doxygen/CMakeLists.txt
- InterfacePython/PipInstaller/setup.py
- InterfacePython/testMakeUpdate.py
- Makefile
- SparseGrids/CMakeLists.txt
* update the Tasmanian identified version to `7.1` development
> Version bump

- Config/CMakeIncludes/CMakeLists.txt
- InterfacePython/PipInstaller/setup.py
* fix the pip version to a canonical form
* the log file now uses the install command so it can be seen by pip
> Small pip fixes

- Doxygen/CMakeLists.txt
* the main Doxygen page report the current git-hash
> added the git hash to the main page

- .jenkins
* using squash of commits, only keep the last doxygen page
> Squash doxygen commits

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tasgridTestHelpers.hpp
The tests still have lingering pre C++11 style of code, cleaned a lot of it an simplified things by a big margin.
> Cleanup sg testing

- CHANGELOG.md
- Doxygen/Installation.md
- Doxygen/InterfacePython.md
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgrid_main.cpp
Fix several missing notes, typos and alignment in the docs.
> Fix doc bugs

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchEvaluate.hpp
- SparseGrids/Benchmarks/benchInterpolationWeights.hpp
- SparseGrids/Benchmarks/benchLoadNeeded.hpp
- SparseGrids/Benchmarks/benchMakeGrid.hpp
- SparseGrids/Benchmarks/bench_main.cpp
* more templated benchmarks, now includes single precision
> Mixed precision benchmark

- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianConfig.in.py
* fix some python paths under windows
> fix python paths under windows

- SparseGrids/tsgGridLocalPolynomial.cpp
* fix performance bug when computing the integrals of local polynomials
> fix performance bug in localp integrals

- Doxygen/tasmanian.css
- search bar input is now 100%
- doxygen result popup is centered
> Update search bar and result popup.

- Addons/testMPI.hpp
- Addons/tsgMPIConstructGrid.hpp
Added a template that can be used for MPI construction on the non-root ranks.
> added worker template

- InterfaceFortran/TasmanianSG.f90
- InterfaceFortran/fortester.f90
- InterfaceFortran/tsgC2Fortran.cpp
- InterfaceMATLAB/CMakeLists.txt
- InterfaceMATLAB/tsgCoreTests.m
- InterfaceMATLAB/tsgGetHSupport.m
- InterfacePython/TasmanianSG.py
- InterfacePython/testUnstructuredData.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tasgridWrapper.hpp
- SparseGrids/tasgrid_main.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* added methods to return the support of the hierarchical basis funcitons
* included all interfaces
> Output support

- InterfaceFortran/fortester.f90
- InterfacePython/testRefinement.py
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridWavelet.cpp
* improved test coverage: cuda cache, construction i/o, exceptions, fortran, and others.
* fixed Fourier and Wavelet bugs with the construction i/o
> Improved test coverage

- Addons/CMakeLists.txt
- InterfaceFortran/CMakeLists.txt
> fix mpich problem with flags

- InterfacePython/TasmanianSG.py
- InterfacePython/testExceptions.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
Tasmanian now accepts CUDA handles and Magma queues initialized by the user.
> Cuda handles

- InterfacePython/TasmanianAddons.py
- InterfacePython/TasmanianConfig.in.py
- InterfacePython/TasmanianDreamSampler.py
- InterfacePython/TasmanianSG.py
- InterfacePython/testBasicIO.py
- InterfacePython/testDream.py
- InterfacePython/testExceptions.py
- InterfacePython/testMakeUpdate.py
- InterfacePython/testMisc.py
* proved python error coverage
* added error checking for the outputs of user provided callable models
* improved the messages when an error occurs
> Improved python exceptions

- Doxygen/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIOHelpers.hpp
* main grid classes now have constructions to read-initialize (using the read methods)
* smart pointers are now constructed with make factory methods
> Better class initialization

- DREAM/tsgDreamLikelyGaussian.hpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
* added override keyword to virtual methods
> added override keyword to virtual methods

- DREAM/tsgDreamState.cpp
- InterfacePython/TasmanianDreamSampler.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
* fix several warnings with clang-tidy and others
> Fix warnings

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgOneDimensionalWrapper.cpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
* fix several bugs with uninitialized variables
* removed the need for every class to have reset in addition to the destructor/constructor
* copy and make commands rely initialize as much as possible (as opposed to overwrite)
> Fix class initialization

- Addons/CMakeLists.txt
* added OMP_NUM_THREADS for the Addon tests
> set the number of omp threads for the addon tests

- Addons/testConstructSurrogate.hpp
- Addons/tsgCandidateManager.hpp
- Addons/tsgMPIConstructGrid.hpp
- DREAM/tsgDreamLikelyGaussian.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgIOHelpers.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* reading is done with a specialized friend template so the logic is separate from the class
* in the future, reading will be done with read constructors
* read constructors are added for dynamic data structures
* all read methods are templated using types
* the main class now uses the IO helper methods
> Update read mechanics

- DREAM/tsgDreamLikelyGaussian.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCacheLagrange.hpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgHardCodedTabulatedRules.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
- SparseGrids/tsgRuleWavelet.cpp
- SparseGrids/tsgRuleWavelet.hpp
* set the destructors to default as opposed to {}
* ensured default constructors initialize the scalars
> improved constructors and destructors

- Addons/CMakeLists.txt
- CMakeLists.txt
- DREAM/CMakeLists.txt
- InterfaceFortran/CMakeLists.txt
- SparseGrids/CMakeLists.txt
* added SOVERSION directives to cmake
* removed some redundant directives
> added soversion to the target libraries

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgHierarchyManipulator.cpp
- SparseGrids/tsgHierarchyManipulator.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
* better encapsulation for the storage classes
* cleaned up some of the setting and initializations
> Better encapsulation

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.hpp
* remove some redundant fills resulting in extraneous mem-writes
* remove some redundant temporaries
> Clean redundant fills

- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
* refactored redundant code about points conversions
* removed more redundant initializations and temporaries
> Improved expressive calls

- SparseGrids/TasmanianSparseGrid.cpp
* added wavelet grids to the error checking for construction methods
> added wavelet to the list of checks

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgIndexSets.hpp
* consistent naming for ownership release
* improved move semantics for cuda domain, engine, and vector
> Consistency with standard

- Addons/CMakeLists.txt
- CMakeLists.txt
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Config/TasmanianConfig.in.cmake
- Doxygen/Installation.md
- InterfaceFortran/CMakeLists.txt
* switch from manual flags and libraries to using the cmake target
* updated the auto-detect logic and the documentation
> Using the MPI targets

- Addons/CMakeLists.txt
- CMakeLists.txt
- Config/TasmanianConfig.in.cmake
- Doxygen/Installation.md
- InterfaceFortran/CMakeLists.txt
- InterfaceFortran/TasmanianSG.f90
* fix warnings, docs, and exports of mpi compilers related to mpich
> Update mpich compatibility

- Addons/CMakeLists.txt
- InterfaceFortran/CMakeLists.txt
- SparseGrids/CMakeLists.txt
> Cmake cleans

- Config/CMakeIncludes/exports.cmake
- Testing/test_post_install.in.sh
* post install tests now install and can be run after the build folder is gone
> installing the post install test

- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgIndexSets.cpp
- SparseGrids/tsgIndexSets.hpp
- SparseGrids/tsgUtils.hpp
* converted some c-style of casts to static or dynamic casts
> Make more cpp ish

- Testing/test_post_install.in.sh
* added the ability to pass cmake options to post-install tests
> added the ability to pass cmake options to post-install tests

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.txt
- InterfaceSwig/FortranExamples/example_sparse_grids.f90
- InterfaceSwig/FortranExamples/example_sparse_grids_02.f90
- InterfaceSwig/FortranExamples/example_sparse_grids_03.f90
- InterfaceSwig/FortranExamples/example_sparse_grids_04.f90
* added fortran 2003 example 4
> added fortran example 4

- InterfaceSwig/CMakeLists.txt
- InterfaceSwig/FortranTests/test_domain.f90
- InterfaceSwig/FortranTests/test_evaluate.f90
- SparseGrids/tsgIndexSets.hpp
* added tests for eval and batch eval (single and double precision)
> Fortran eval tests

- InterfaceSwig/CMakeLists.txt
- InterfaceSwig/FortranTests/fortranswigtester.f90
- InterfaceSwig/FortranTests/test_update_grid.f90
* added tests to the fortran wrappers for update grids
> add update grid tests

- Addons/tsgCConstructSurrogate.cpp
- Addons/tsgCandidateManager.hpp
- InterfacePython/testAddons.py
* fixed couple of construction bugs related to batch models
> Fix batch construct bug

- Doxygen/Installation.md
- InterfacePython/PipInstaller/README.md
- InterfacePython/PipInstaller/pyproject.toml
- InterfacePython/PipInstaller/setup.py
* fixed the python pip-dependencies and documentation
> Pip dependencies

- CMakeLists.txt
- Config/CMakeIncludes/setup_message.cmake
* fix a bug with the xsdk log file
> fix xsdk bug with log files

- Addons/testConstructSurrogate.hpp
- Addons/tsgConstructSurrogate.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* added persistent acceleration context
> Unified acceleration context

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
* reduced the pre-processor macros and renamed cuda variables to gpu
> Preprocessor cleanup

- CHANGELOG.md
- Doxygen/Installation.md
- SparseGrids/tsgEnumerates.hpp
* updated the documentation of the acceleration options
> updated the acceleration docs

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchEvaluate.hpp
- SparseGrids/Benchmarks/benchLoadNeeded.hpp
- SparseGrids/Benchmarks/bench_main.cpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* wavelets now respect the sparse-dense selection
* localp grids use the new sparse-dense selection
* added to the benchmark setup
> Sparse-dense updated acceleration logic

- InterfaceTPL/tsgBlasWrappers.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* gmres solver is templated and is utilizing blas
> template the gmres solver and utilize blas

- InterfaceTPL/tsgBlasWrappers.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* added lapack general least-squares solver in addition to the simple algorithm
> Using lapack gels

- Doxygen/CMakeLists.txt
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgLinearSolvers.hpp
* updated blas-lapack and cuda docs
> updated blas-lapack and cuda docs

- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgLinearSolvers.cpp
> Mscv fixes

- Addons/CMakeLists.txt
- Addons/testAddons.cpp
- Addons/testLoadUnstructured.hpp
- Addons/tsgLoadUnstructuredPoints.hpp
- Config/AltBuildSystems/Makefile.in
- Config/CMakeIncludes/FindTasmanianCudaMathLibs.cmake
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgGpuWrappers.hpp
- InterfaceTPL/tsgTPLWrappers.hpp
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/gridtest_main.cpp
- SparseGrids/tasgridCLICommon.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* added load-unstructured data method using the cusolver library
> Cusolve methods

- Addons/testLoadUnstructured.hpp
- InterfaceTPL/tsgBlasNull.hpp
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgTPLWrappers.hpp
- SparseGrids/CMakeLists.txt
- SparseGrids/Makefile
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaLinearAlgebra.hpp
- SparseGrids/tsgCudaLoadStructures.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridFourier.hpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridGlobal.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgGridWavelet.hpp
- SparseGrids/tsgLinearSolvers.cpp
* added no-op methods in place of preprocessor macros
> Preprocessor reduction

- Addons/testLoadUnstructured.hpp
- CHANGELOG.md
- Doxygen/CMakeLists.txt
- InterfaceSwig/generated/tasmanianFORTRAN_wrap.cxx
- InterfaceTPL/tsgBlasWrappers.hpp
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgCudaWrappers.hpp
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgGpuWrappers.hpp
- InterfaceTPL/tsgMagmaWrappers.hpp
- InterfaceTPL/tsgTPLWrappers.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridCore.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgUtils.hpp
* added unstructured data construction using magma out-of-core methods
* updated the handle management and documentation
> Using magma ooc

- Addons/testLoadUnstructured.hpp
- Addons/tsgLoadUnstructuredPoints.hpp
- Doxygen/CMakeLists.txt
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgGpuNull.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgCudaLinearAlgebra.hpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* basis matrix in the unstructured construction now uses cuda acceleration
* improved the documentation across the data and backends
> using gpu acceleration for matrix construction

- Config/CMakeIncludes/FindTasmanianCudaMathLibs.cmake
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgSupportCuda8.hpp
* restore cuda 8 support for the mid-year release (will drop right after)
> Restore cuda8 support

- Doxygen/Installation.md
- InterfaceTPL/tsgGpuNull.cpp
* fix some problem with msvc 2017 and explicit instantiation of templates
* updated the docs
> Msvc fixes

- Addons/tsgAddonsCommon.hpp
- Doxygen/CMakeLists.txt
- InterfaceTPL/tsgBlasWrappers.hpp
- InterfaceTPL/tsgGpuWrappers.hpp
- InterfaceTPL/tsgTPLWrappers.hpp
- SparseGrids/tsgCacheLagrange.hpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
- SparseGrids/tsgRuleLocalPolynomial.hpp
- SparseGrids/tsgUtils.hpp
* fixing typos in the groups and internal docs
> update the groups and interna/external split

- Addons/tsgCandidateManager.hpp
- Addons/tsgConstructSurrogate.hpp
- InterfacePython/CMakeLists.txt
- InterfacePython/PipInstaller/setup.py
* enabled osx framework install
* made small adjustments
> Python pip fixes

- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- Doxygen/Installation.md
- InterfacePython/PipInstaller/setup.py
- README.md
- SparseGrids/TasmanianSparseGrid.h
- SparseGrids/TasmanianSparseGridWrapC.cpp
* bumped the version and some documentation to 7.1
> Version 71

- Addons/tsgLoadUnstructuredPoints.hpp
- Config/CMakeIncludes/FindTasmanianRocm.cmake
- Config/CMakeIncludes/add_dependencies_target.cmake
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Config/TasmanianConfig.in.cmake
- InterfacePython/testConfigureData.in.py
- InterfaceSwig/FortranTests/test_evaluate.f90
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgHipWrappers.cpp
- InterfaceTPL/tsgHipWrappers.hpp
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgLinearSolvers.cpp
* added AMD accelerated linear algebra through rocblas and rocsparse
> Rocm blas and sparse support

- Config/CMakeIncludes/FindTasmanianRocm.cmake
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- DREAM/tsgDreamLikelyGaussian.cpp
- InterfacePython/TasmanianDreamLikely.py
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgHipWrappers.cpp
- Makefile
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
- SparseGrids/tsgCudaLinearAlgebra.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgHipKernels.hip.cpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
* instantiated the cuda kernels in a hip build using hipcc
> added hip instantiation of the gpu kernels using hipcc

- Config/CMakeIncludes/FindTasmanianRocm.cmake
- Config/TasmanianConfig.in.cmake
- InterfaceTPL/tsgHipWrappers.cpp
- InterfaceTPL/tsgHipWrappers.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgLinearSolvers.cpp
* added plu method from rocsolver
> added plu method from rocsolver

- Config/CMakeIncludes/CMakeLists.txt
- Config/CMakeIncludes/add_dependencies_target.cmake
- InterfaceSwig/CMakeLists.txt
- InterfaceSwig/generated/tasmanian.f90
- InterfaceSwig/generated/tasmanianFORTRAN_wrap.cxx
* update the swig fortran interface
> Fix swig build

- InterfaceSwig/FortranTests/test_common.f90
- InterfaceSwig/FortranTests/test_evaluate.f90
- InterfaceSwig/TasmanianSparseGrid.i
- InterfaceSwig/generated/tasmanian.f90
- InterfaceSwig/generated/tasmanianFORTRAN_wrap.cxx
* evaluate fast is now added to the Fortran module
> added swig instantiation for evaluate fast with float and double

- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgCudaWrappers.hpp
- InterfaceTPL/tsgMagmaWrappers.hpp
* added support for the new cuda 11 API
> added support for the new cuda 11 API

- InterfaceTPL/tsgHipWrappers.cpp
- SparseGrids/tsgHipKernels.hip.cpp
- SparseGrids/tsgLinearSolvers.cpp
* updated the build system to rocm 3.5 (template instantiation had to change)
* added a least squares solver for double-precision real problems (using lq factorization)
> Added rocm solver for least-squares

- Config/CMakeIncludes/FindTasmanianRocm.cmake
- InterfaceTPL/tsgHipWrappers.hpp
- SparseGrids/tsgCudaBasisEvaluations.hpp
* updated compatibility to Rocm 3.7
> Rocm 37 update

- .jenkins
- docker/Dockerfile.rocm
* added rocm docker image and a rocm test
> Adding ROCm test to the CI

- Doxygen/Installation.md
- install
* update the install script and documentation
> Updated docs

- CHANGELOG.md
- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- Config/CMakeIncludes/master_targets.cmake
- Config/TasmanianConfig.in.cmake
- Doxygen/Installation.md
- Makefile
* documentation and change log updates
* version bump to 7.3 - release candidate
* added the `::shared` and `::static` targets for backwards compatibility
> Doc updates

- .jenkins
- CMakeLists.txt
- Config/CMakeIncludes/FindTasmanianDpcpp.cmake
- Config/CMakeIncludes/add_dependencies_target.cmake
- Config/CMakeIncludes/helper_macros.cmake
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- Config/CMakeIncludes/setup_message.cmake
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgDpcppWrappers.hpp
- SparseGrids/CMakeLists.txt
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDpcppKernels.cpp
* added dpc++ option
* added the oneapi mkl link
* linked to all the libraries
> added dpcpp option to cmake with the link libraries

- Addons/tsgLoadUnstructuredPoints.hpp
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgGpuWrappers.hpp
- InterfaceTPL/tsgHipWrappers.cpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgCudaKernels.cu
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgGridSequence.hpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgHipKernels.hip.cpp
- SparseGrids/tsgLinearSolvers.cpp
* added the acceleration context to the gpu kernels
* added the acceleration context to the gpu linear algebra
* no needed for hip and cuda, but needed for intel
> added the acceleration context to all kernels and gpu method calls

- Addons/testAddons.cpp
- InterfacePython/CMakeLists.txt
- InterfacePython/testConfigureData.in.py
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgDpcppWrappers.hpp
- InterfaceTPL/tsgGpuWrappers.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDpcppKernels.cpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgLinearSolvers.cpp
- SparseGrids/tsgLinearSolvers.hpp
Added linear algebra backend for the DPC++ backend
* added sparse and dense matrix/vector multiply
* added PLU solver
> DPC++ linear algebra

- InterfaceMATLAB/tsgMakeFilenames.m
Add process ID for evaluating the interpolant with Matlab parallel toolbox
> for parallel evaluations in matlab

- Config/CMakeIncludes/add_dependencies_target.cmake
- InterfaceTPL/tsgDpcppWrappers.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.cpp
- SparseGrids/tsgDpcppBasisEvaluations.hpp
- SparseGrids/tsgDpcppKernels.cpp
* added DPC++ kernels for the different types of grids
* added kernels and tests for domain transformations
> Dpcpp update

- InterfacePython/PipInstaller/setup.py
* remove the github ci images from the python description
> update the readme mod

- Config/CMakeIncludes/all_examples.cmake
- InterfaceSwig/CMakeLists.txt
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgDpcppWrappers.hpp
- SparseGrids/tsgDpcppKernels.cpp
* enabled the oneapi sparse methods
* enable auto selection gpu-cpu and fortran-oneapi
> Onemkl sparse

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/tasgridTestHelpers.hpp
* fixed a missing domain transform reset under non-cuda gpu platforms
* updated the sparse test to handle unsorted column indexes
> Rocm fixes

- SparseGrids/tsgCudaBasisEvaluations.hpp
* allows for a more flexible selection in number of threads and removes the assumption of 32-threads per warp
> removed some 32-threads per wrap assumptions

- Addons/testAddons.cpp
- Addons/tsgLoadUnstructuredPoints.hpp
- Config/CMakeIncludes/FindTasmanianDpcpp.cmake
- Config/CMakeIncludes/FindTasmanianRocm.cmake
- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgHipWrappers.cpp
- SparseGrids/gridtest_main.cpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDpcppBasisEvaluations.hpp
- SparseGrids/tsgDpcppKernels.cpp
* added baseline QR implementation for dpc++
* fixed some of the kernels related to dpc++
> Dpcpp updates

- Addons/CMakeLists.txt
- Config/CMakeIncludes/helper_macros.cmake
- DREAM/CMakeLists.txt
- InterfaceFortran/CMakeLists.txt
- InterfacePython/CMakeLists.txt
- InterfaceSwig/CMakeLists.txt
- SparseGrids/CMakeLists.txt
* consolidate cmake test options
> consolidate cmake test options

- CMakeLists.txt
- InterfacePython/PipInstaller/setup.py
- README.md
> release 7.5

- .github/workflows/build-windows.yaml
- README.md
Two files modified:
- `.github/workflows/build-windows.yaml` add functionality of the windows CI
- `README.md` adds the status badge
> add windows CI

- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
* added test using external sycl queue
> added test using external sycl queue

- Config/CMakeIncludes/all_examples.cmake
- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgHipWrappers.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
* added manual rocm handles with testing
> Hip updates

- InterfaceTPL/tsgCudaWrappers.cpp
- InterfaceTPL/tsgCudaWrappers.hpp
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgGpuNull.cpp
- InterfaceTPL/tsgHipWrappers.cpp
- InterfaceTPL/tsgHipWrappers.hpp
- InterfaceTPL/tsgMagmaWrappers.hpp
- SparseGrids/CMakeLists.txt
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgAcceleratedHandles.hpp
* better logic for handling ownership of c-style handles for cublas/rocblas/sycl
* fixed bugs with order of deletion of objects
> Better handles logic

- Config/CMakeIncludes/CMakeLists.txt
- InterfacePython/TasmanianSG.py
- InterfacePython/testBasicIO.py
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tasgridUnitTests.cpp
- SparseGrids/tasgrid_main.cpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
* exposed manual gpu queues and handles to the main api
* reported the gpu backend through the interfaces: cli, python, and cmake
> Safer manual handles

- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
- SparseGrids/tsgGridGlobal.hpp
* added new constructor for the CustomTabulated rule
* added new makeGlobalGrid() logic that accepts a CustomTabulated rule
> Update custom rule

- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridExternalTests.hpp
* simplified error reporting in some tests
> simplified error reporting in some tests

- InterfacePython/TasmanianSG.py
- InterfacePython/sandbox.py
- InterfacePython/testMakeUpdate.py
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tsgCoreOneDimensional.cpp
- SparseGrids/tsgCoreOneDimensional.hpp
Create Python code that wraps the C++ CustomTabulated class.
> Add a Python CustomTabulated Class

- Testing/CMakeLists.test.cmake
* moved python-post-install testing to ctest
> moved all testing to ctest

- .jenkins
- docker/Dockerfile.rocm
> update the rocm ci

- CMakeLists.txt
- Config/CMakeIncludes/all_examples.cmake
- InterfaceSwig/TasmanianSparseGrid.i
- InterfaceSwig/generated/tasmanian_swig.f90
- InterfaceSwig/generated/tasmanian_swigFORTRAN_wrap.cxx
* updated the Tasmanian swig files and interface
> Updated swig files

- InterfacePython/TasmanianSG.py
- InterfacePython/testExceptions.py
- InterfacePython/testRefinement.py
- InterfaceSwig/generated/tasmanian_swig.f90
- InterfaceSwig/generated/tasmanian_swigFORTRAN_wrap.cxx
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridLocalPolynomial.hpp
* extended the remove points method to keep a fixed number of points
> Compress grid by number of points

- InterfacePython/TasmanianSG.py
- InterfacePython/testBasicIO.py
- InterfacePython/testCommon.py
- InterfacePython/testExceptions.py
- SparseGrids/TasmanianSparseGridWrapC.cpp
- SparseGrids/tsgCoreOneDimensional.cpp
Includes some changes to the exceptions thrown and file input types.
> Bug fixes + Python unit tests for the CustomTabulated class.

- CHANGELOG.md
- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- InterfacePython/PipInstaller/setup.py
- Makefile
> marked as release candidate

- Config/CMakeIncludes/add_dependencies_target.cmake
- SparseGrids/CMakeLists.txt
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridWrapper.cpp
- SparseGrids/tasgridWrapper.hpp
- SparseGrids/tasgrid_main.cpp
An example of a command line call is:
```
./tasgrid -meq -depth 5 -shift 1.0 -weightfile sinc0.txt -description "Test Exoquad" -symmetric -outfile exoquad.ct -print
```
where `sinc0.txt` contains a weight function surrogate/intepolant that has been generated beforehand (see [here](https://github.com/ORNL/TASMANIAN/files/7260218/sinc0.txt) for an example).
> CLI for creating Exotic quadratures 

- SparseGrids/CMakeLists.txt
- SparseGrids/tasgridExternalTests.cpp
- SparseGrids/tasgridLogs.in.hpp
* fix the gauss patterson table search
> fix the gauss patterson table search

- Tasgrid/tasgrid_main.cpp
> fixed some tasgrid docs

- .github/workflows/build-macos.yaml
> moved ci to osx 11

- InterfacePython/TasmanianSG.py
- SparseGrids/TasmanianSparseGrid.hpp
Adds the functions `getAnisotropicRefinement()` and `getSurplusRefinement()` to the Python interface.
> Add get refinement functions 

- DREAM/CMakeLists.txt
- DREAM/Optimization/tsgParticleSwarm.cpp
- InterfacePython/sandbox.py
* fix some warnings
* add the optimizations tests to ctest
* fix the python include in the sandbox.py
* passing a lambda object by value
> Fix shadow warnings

- InterfacePython/PipInstaller/setup.py
> fix error in setuptools

- DREAM/Optimization/tsgParticleSwarm.hpp
- Doxygen/CMakeLists.txt
- Makefile
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/gridtestUnitTests.cpp
- SparseGrids/tsgCacheLagrange.hpp
- SparseGrids/tsgEnumerates.hpp
- SparseGrids/tsgIOHelpers.hpp
> Clean conflicts

- Doxygen/InterfaceCLI.md
- InterfaceMATLAB/CMakeLists.txt
- InterfaceMATLAB/tsgCoreTests.m
- InterfaceMATLAB/tsgDifferentiate.m
- InterfaceMATLAB/tsgGetDifferentiationWeights.m
- Tasgrid/tasgridWrapper.cpp
- Tasgrid/tasgridWrapper.hpp
- Tasgrid/tasgrid_main.cpp
I have tested it in MATLAB 202a on `titanmath` and it seems to be working as intended.
> Add CLI and MATLAB wrappers for grid differentiation

- Config/CMakeIncludes/all_examples.cmake
- Config/CMakeLists.examples.cmake
- Doxygen/CMakeLists.txt
- InterfacePython/CMakeLists.txt
- InterfacePython/example_sparse_grids_11.py
- SparseGrids/Examples/example_sparse_grids.cpp
- SparseGrids/Examples/example_sparse_grids_11.cpp
* added example for unstructured grid construction
> added example for unstructured grid construction

- DREAM/Optimization/TasmanianOptimizationWrapC.cpp
- InterfacePython/CMakeLists.txt
- InterfacePython/TasmanianGradientDescent.py
- InterfacePython/TasmanianOPT.py
- InterfacePython/sandbox.py
Some examples of how to use the wrapper functions are given in `Python/sandbox.py`. These will need to be removed before merging.
> Add Python wrappers for gradient descent

- DREAM/Optimization/tasdreamOptimizationTests.cpp
- DREAM/Optimization/tsgOptimizationUtils.hpp
Move the gradient descent test function from the utilities file to the testing file.
> Small re-organization

- InterfacePython/TasmanianSG.py
- InterfacePython/testMisc.py
- SparseGrids/TasmanianSparseGridWrapC.cpp
This PR also includes a set of unit tests that check dimensional consistency and ordering.
> Add Python sparse grid differentiation wrapper

- InterfacePython/example_optimization_01.py
- InterfacePython/example_optimization_02.py
NOTE: these changes depend on PR #695 and will only be ready (and rebased) once that PR is approved.
> Add Python optimization examples

- Addons/tsgAddonsCommon.hpp
- Config/CMakeIncludes/add_dependencies_target.cmake
- DREAM/CMakeLists.txt
* the optimization header is now included through `Tasmanian.hpp`
> added the optimization header to the master

- Makefile
* fix optimization in gnu make
> fix optimization in gnu make

- Config/CMakeIncludes/FindTasmanianCudaMathLibs.cmake
- Config/TasmanianConfig.in.cmake
* switching to using cmake find-cuda-toolkit when cmake supports it
> fix find-cuda-libs on newer cmake versions

- SparseGrids/gridtestExternalTests.cpp
- SparseGrids/gridtestTestHelpers.hpp
- SparseGrids/tsgGridLocalPolynomial.cpp
* block sycl kernels for localp grids
> block sycl kernels for localp grids

- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- Makefile
* version bump to release candidate
> bump to release candidate

- DREAM/Optimization/TasmanianOptimization.hpp
- DREAM/Optimization/tsgGradientDescent.cpp
- DREAM/Optimization/tsgGradientDescent.hpp
- DREAM/Optimization/tsgOptimizationUtils.hpp
- DREAM/Optimization/tsgParticleSwarm.hpp
> documentation cleanup

- Doxygen/Installation.md
> last doc updates

- DREAM/Optimization/tsgGradientDescent.hpp
- Doxygen/CMakeLists.txt
- Doxygen/Contributors.md
- InterfacePython/PipInstaller/setup.py
- README.md
* updating the Tasmanian web-page
> Contributors

- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- InterfacePython/PipInstaller/setup.py
- Makefile
- README.md
> begin work on the next release

- .github/workflows/build-macos.yaml
- .github/workflows/build-ubuntu.yaml
- Addons/testMPI.hpp
- docker/Dockerfile.cuda
- docker/Dockerfile.rocm
* various ci for github and jenkins
> update github ci os

- SparseGrids/CMakeLists.txt
* cleaner selection of files for each backend
> using bools to load sources

- InterfacePython/PipInstaller/setup.py
> fix deprecated usage

- Addons/testLoadUnstructured.hpp
- InterfacePython/testAcceleration.py
- InterfacePython/testConfigureData.in.py
- InterfaceTPL/tsgDpcppWrappers.cpp
- InterfaceTPL/tsgDpcppWrappers.hpp
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/gridtestExternalTests.cpp
- SparseGrids/gridtestExternalTests.hpp
- SparseGrids/gridtestTestHelpers.hpp
- SparseGrids/tsgAcceleratedDataStructures.hpp
- SparseGrids/tsgDpcppBasisEvaluations.hpp
* deprecated sycl calls and removed workaround compiler bugs
> fixing deprecated calls

- DREAM/Optimization/tsgGradientDescent.cpp
- DREAM/Optimization/tsgParticleSwarm.cpp
- SparseGrids/tsgGridLocalPolynomial.cpp
> Acceleration fixes

- Config/CMakeIncludes/FindTasmanianDpcpp.cmake
* switch to oneapi shared libs
> switch to oneapi shared libs

- SparseGrids/tsgIndexManipulator.cpp
* fix bug with anisotropic refinement
> fix bug with anisotropic refinement

- Doxygen/InterfaceMATLAB.md
- InterfaceMATLAB/CMakeLists.txt
- InterfaceMATLAB/tsgCoreTests.m
- InterfaceMATLAB/tsgGetCandidateConstructionAnisotropic.m
- InterfaceMATLAB/tsgGetCandidateConstructionSurplus.m
- InterfaceMATLAB/tsgLoadConstructedPoints.m
- InterfaceMATLAB/tsgUsingConstruction.m
- SparseGrids/tsgCacheLagrange.hpp
- SparseGrids/tsgDConstructGridGlobal.cpp
- SparseGrids/tsgDConstructGridGlobal.hpp
- SparseGrids/tsgGridFourier.cpp
- SparseGrids/tsgGridGlobal.cpp
- SparseGrids/tsgIndexManipulator.hpp
- SparseGrids/tsgOneDimensionalWrapper.hpp
- Tasgrid/tasgridWrapper.cpp
- Tasgrid/tasgridWrapper.hpp
- Tasgrid/tasgrid_main.cpp
* added method for dynamic construction to MATLAB
> Matlab dynamic construction

- SparseGrids/TasmanianSparseGrid.hpp
* add overloads to read directly from strings
> added overloads for string

- InterfaceMATLAB/CMakeLists.txt
- InterfaceMATLAB/tsgCoreTests.m
- SparseGrids/TasmanianSparseGrid.cpp
- SparseGrids/TasmanianSparseGrid.hpp
- SparseGrids/gridtestUnitTests.cpp
- Tasgrid/tasgridWrapper.cpp
- Tasgrid/tasgridWrapper.hpp
* improved the ugly code in the cli interface
> Better tasgrid wrapper

- InterfaceTPL/tsgCudaWrappers.cpp
* adding a workaround for a cuda 12 api bug
> workaround cuda 12 api bug

- docker/Dockerfile.doxygen
* update the doxygen docker container
> update the docker container

- Addons/tsgAddonsCommon.hpp
- CHANGELOG.md
- DREAM/Optimization/TasmanianOptimization.hpp
- SparseGrids/tsgGridLocalPolynomial.hpp
> Doc update

- Config/CMakeIncludes/FindTasmanianDpcpp.cmake
- Doxygen/Installation.md
- SparseGrids/CMakeLists.txt
* Tasmanian now sets the sycl flags internally
> Sylc flags

- .jenkins
* reduce concurrency for mpi build
> reduce the number of threads add concurrent tests when using mpi

- InterfaceSwig/FortranTests/test_evaluate.f90
> fix oneapi fortran test

- DREAM/CMakeLists.txt
- DREAM/Optimization/tsgParticleSwarm.cpp
- SparseGrids/tsgIndexManipulator.cpp
> Performance improvements

- SparseGrids/Examples/example_sparse_grids_11.cpp
* fix some typos in the examples
> fix coule of typos

- .github/workflows/build-macos.yaml
- .github/workflows/build-ubuntu.yaml
- .github/workflows/build-windows.yaml
* update the compilers in the github runners
> update compilers in the runners

- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- Makefile
> set new version number

- InterfaceTPL/tsgHipWrappers.cpp
- InterfaceTPL/tsgHipWrappers.hpp
- SparseGrids/gridtestUnitTests.cpp
> fix compiler warnings

- CMakeLists.txt
- InterfacePython/PipInstaller/setup.py
> set version 8.0

- SparseGrids/tsgGridSequence.cpp
* switch the coefficient computation of sequence grids to use generalized Kronecker algorithm
> Sequence grids using generalized Kronecker algorithm

- SparseGrids/tsgGridSequence.cpp
- SparseGrids/tsgIndexManipulator.cpp
- SparseGrids/tsgIndexManipulator.hpp
* switch to faster global kronecker algorithm for computing tensor weights
> Fast tensor weights

- SparseGrids/Benchmarks/benchCommon.hpp
- SparseGrids/Benchmarks/benchRefine.hpp
- SparseGrids/Benchmarks/bench_main.cpp
- SparseGrids/CMakeLists.txt
- SparseGrids/tsgGridLocalPolynomial.cpp
* added a benchmark for the set anisotropic and surplus refinements
> added benchamrk to test refinement

- SparseGrids/tsgGridLocalPolynomial.cpp
- SparseGrids/tsgGridWavelet.cpp
- SparseGrids/tsgIndexManipulator.cpp
* expose parallelism in more refinement algorithms
> Expose more parallelism

- InterfacePython/testCommon.py
* relax testing tol, some systems are not bitwise reproducible
> relax testing tol, some systems are not bitwise reproducible

- .jenkins
* update the rocm docker label
> update the rocm docker label

- CHANGELOG.md
- Doxygen/Installation.md
* update the docs w.r.t. apple silicon
> updated documentation for apple

- SparseGrids/gridtestExternalTests.cpp
- SparseGrids/tsgIndexManipulator.cpp
* found race condition in a lambda using internal caching called inside openmp block
closes #759
> fix race condition

- CHANGELOG.md
- Doxygen/Installation.md
- InterfacePython/PipInstaller/setup.py
> Small update

- Tasgrid/tasgridWrapper.cpp
* fix output bug in quadrature
> fix output bug

- InterfacePython/TasmanianSG.py
- SparseGrids/tsgGridWavelet.cpp
Fix a bug related to the wavelet grids changing the GPU contect.
> fix bug when wavelet grids change the gpu context

- Config/TasmanianENVsetup.in.sh
Update the post-install testing for ROCm.
> fix rocm post-install test

- Config/CMakeIncludes/sanity_check_and_xsdk.cmake
* updated support for the Intel ifx Fortran compiler
> Fix ifx compiler

- CMakeLists.txt
- Doxygen/Installation.md
- Doxygen/header.html
- InterfacePython/PipInstaller/setup.py
> New release

- CHANGELOG.md
- CMakeLists.txt
- Config/AltBuildSystems/TasmanianConfig.hpp
- InterfacePython/PipInstaller/setup.py
- Makefile
> version bump for development

- .github/workflows/build-ubuntu.yaml
- .github/workflows/build-windows.yaml
- Addons/testLoadUnstructured.hpp
- CMakeLists.txt
- DREAM/Optimization/tasdreamOptimizationTests.cpp
- InterfaceTPL/tsgCudaWrappers.cpp
> Support cuda13
