ORNL/TASMANIAN

CMakeLists.txt

This should address your comment about using `-j<num_procs>` when running the tests in #10 
Basically we can specify how many process slots a test requires. I chose 4 as the default. I can change it if you like. Note that I only listed `Tasgrid` and `Tasdream`. Let me know if I should include others.

Specify number of threads to use in tests

---

CMakeLists.txt
docker/jenkins/build.sh

Testing make install, make test_install
Adding flags: -Wshadow -pedantic
Set Tasmanian_TESTS_OMP_NUM_THREADS=4, otherwise testing takes too long

Added (test_)install, shadow+pedantic, omp_num_threads=4

---

DREAM/TasmanianDREAM.cpp
DREAM/tasdreamExternalTests.cpp
DREAM/tasdreamExternalTests.hpp

* added custom random number generator for all DREAM tests; this will remove the dependence on the compiler provided rand() calls and remove compiler dependence for the tests
* DREAM uses the overwritten random number generator to select the chains for computing increments; there is no place in the code left, where compiler provided rand() would be used when a custom rng is provided

Custom random generator for DREAM

---

Config/AltBuildSystems/TasmanianConfig.hpp
Config/AltBuildSystems/testTSG.py
InterfacePython/testTSG.in.py
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgEnumerates.hpp

* Acceleration fall-back logic was split between two functions `evaluateFast()` and `evaluateBatch()`, not it is all in one place
* Added MAGMA to the logic
* Updated the tests to account for the changes
* Propagated to legacy build system
**Note:** there are two layers of fall-back logic:
* **layer 1** the user specifies a given mode, which was not used on build time, then fall-back to the *next-best* from the options available on compile time.
* **layer 2** is specific to each type of grid and covers cases that have not been implemented yet, as well as use of non-existing functions (e.g., ensure we don't make calls to CUDA when CUDA is missing). The second layer **does not** guarantee the use of *next-best*.

Acceleration fallback logic

---

SparseGrids/tasgridExternalTests.cpp

test tolerances have to be tight to ensure accuracy, but they also rely on random sampling and newer tests need some time to stabilize

Adjust test tolerance

---

Config/AltBuildSystems/TasmanianConfig.hpp
Config/TasmanianConfig.in.hpp
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgrid_main.cpp

* All Tasmanian `cmake` options can be retrieved from the compiled library
* The compiled options specified per target are created automatically
* The user specifies the build type and additional flags
* Therefore, with the correct cmake lists file (from the git commit ID), the Tasmanian options, and the build type with the cxx flags, a specific build of Tasmanian can be reproduced exactly
* This fulfils the xSDK policy M8

Add compile options info

---

InterfaceMATLAB/CMakeLists.txt
install

* have cmake create the MATLAB work folder (if missing)
* the install script uses only the work folder, no need for an On/Off variable
* the install script still creates the MATLAB work and converts relative paths (relative to the source folder) to absolute path

Cmake creates matlab folder

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgGridFourier.cpp

* Add spaces between first two entries in `TasgridWrapper::getEvalHierarchySparse()`
* Handle integration differently in the absence of a conformal map
* Fix bug in `setHierarchicalCoefficients()` when grid has no loaded values

Fourier fixes

---

InterfaceMATLAB/tsgCoreTests.m
InterfaceMATLAB/tsgEvaluateHierarchy.m
InterfaceMATLAB/tsgGetHCoefficients.m
InterfaceMATLAB/tsgLoadHCoefficients.m
InterfaceMATLAB/tsgMakeFourier.m
InterfaceMATLAB/tsgMakeQuadrature.m
InterfaceMATLAB/tsgReadMatrix.m
InterfaceMATLAB/tsgReloadGrid.m
InterfaceMATLAB/tsgWriteMatrix.m
SparseGrids/tsgGridFourier.cpp

This branch adds a MATLAB wrapper for the Fourier basis. Changes:
* `tsgReadMatrix.m` now has a boolean flag `bIsComplex`; `tsgWriteMatrix.m` automatically detects whether the matrix is complex
* added `tsgMakeFourier.m`
* fixed a bug that was causing all-zero quadrature weights for the Fourier rule when using `./tasgrid -makequadrature` (source was in `tsgCoreOneDimensional.cpp`)
* added extra case to `printGridStats` in `TasmanianSparseGrid.cpp` so that the MATLAB interface can detect a Fourier rule
* small formatting changes

MATLAB interface for Fourier

---

SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgGridLocalPolynomial.hpp

* added buffer for `cusparseDmatveci()`, which is needed even though CUDA manual indicates otherwise
* added sort for the sparse vectors in `tsgGridLocalPolynomial.hpp`
* increased the size of the tests to that vectors with more non-zeros will be tested

Fix cusparse buffer and order bug

---

Config/AltBuildSystems/TasmanianSG.py
Config/AltBuildSystems/TasmanianSG.windows.py
Config/AltBuildSystems/testTSG.py
InterfacePython/TasmanianSG.in.py
InterfacePython/testTSG.in.py

* added the new rule to the python interface (not sure how the commit dropped from the large pull-request)
* fixed python tests so that bit-wise reproducibility is not expected for Fourier grids and other grids that are tested with non-integer nodes

Python fixes

---

SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCudaKernels.cu
SparseGrids/tsgCudaLinearAlgebra.hpp
SparseGrids/tsgCudaMacros.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp

* merged `#pragma` statements after merging Tasmanian_ENABLE_CUDA and CUBLAS
* merged dense mat-mat and mat-vec calls to cuBlas and MAGMA
* removed code from *failed experiments*
* blocked old fallback code used as placeholder for MAGMA (still potentially useful for debugging)
* removed unnecessary fallback calls for missing acceleration modes
* updated comments

Cuda cleanup

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tsgCudaBasisEvaluations.hpp
SparseGrids/tsgCudaKernels.cu
SparseGrids/tsgEnumerates.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp

* cleaned old experiments from sparse-dense logic in localp grids
* reworked the logic for only two algorithms (3 options, sparse, dense, auto)
* the auto switch happens based on `num_dimensions` as indicated to be the critical factor in the benchmark tests

updated sparse-dense logic in local grids

---

SparseGrids/tsgGridLocalPolynomial.cpp

fix bug where level limits of -1 are not properly interpreted in localp grids

fix bug with refinement level limits and localp grids

---

SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgGridFourier.cpp

* Fourier grids is set to return const pointer to the internal coefficients data structure, consistent behavior with other grids

fixed fourier copy, const pointer is returned to the internal data

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridExternalTests.cpp

* GPU basis evaluation tests compute the CPU reference solution only once (was redundant)
* The test now correctly executes on each detected GPU
* Fixed a bug related to the switch of GPUs (GPU could be set, but changing it later resulted in crash)

Speedup gpu2gpu tests

---

CMakeLists.txt
Config/CMakeLists.examples.txt
Config/TasmanianConfig.in.cmake

* the package config offers a more elegant way to handle this
* if old version of cmake is used to build Tasmanian, then package config will define `Tasmanian_CXX_FLAGS` to compensate for the missing `OpenMP_CXX_LIBRARIES`

moved the OpenMP hack to the package confing

---

SparseGrids/tasgridExternalTests.cpp

* `ExternalTester::getError()` is at the bottom of most math consistency tests
* replaced the `new double[]` arrays with `std::vector`, wherever possible without modifying the library API

Vector experiments

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgGridWavelet.hpp

* only the interface of `TasmanianSparseGrid` should return dynamically allocated pointers for backwards compatibility, e.g., `double* getPoints()`
* the individual grids do not need to implement such methods, e.g., there should be no `double *GridGlobal::getPoints()`, only `void GridGlobal::getPoints(double x[])`

Remove redundant internal api

---

SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCudaMacros.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgIndexSets.hpp

* replaced numerous instances of `new[]` arrays with `std::vector` in `GridLocalPolynomial` class 
* had to modify several other classes to accommodate the change
* several classes now have dual API accepting `int[]` and `std::vector`

Add vector to internals of localp grids

---

InterfaceMATLAB/CMakeLists.txt

added cmake MATLAB target and proper copy dependence for the MATLAB script files, now changes to the source propagate to the build directory without reconfiguring the build system

Changes to MATLAB source do not trigger reconfigure of cmake

---

DREAM/Examples/example_dream.cpp
DREAM/TasmanianDREAM.cpp
DREAM/TasmanianDREAM.hpp
DREAM/tasdreamBenchmark.cpp
DREAM/tasdreamExternalTests.cpp
DREAM/tasdreamTestPDFs.cpp
DREAM/tasdreamTestPDFs.hpp
DREAM/tdrCorePDF.cpp
DREAM/tdrCorePDF.hpp

* `std::vector` API for DREAM and most internal arrays are converted
* old API is still supported with implementing `int getAPIversion()` that returns `5` or less
* if using API version prior to 6, the vector functions can be left empty
* the new API applies to classes inheriting from `ProbabilityWeightFunction` and `CustomModelWrapper`
* many rests and internal API has also been converted to `std::vectors`

Dream vector api

---

DREAM/Examples/example_dream.cpp
DREAM/TasmanianDREAM.cpp
DREAM/tasdreamExternalTests.cpp
DREAM/tasdreamExternalTests.hpp
DREAM/tasdreamTestPDFs.cpp
SparseGrids/Examples/example_sparse_grids.cpp
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgIndexSets.cpp
SparseGrids/tsgIndexSets.hpp

* fixed conversion warnings
* whenever there is a chance to multiply two large numbers and overflow `int`, set one of them to `size_t`
* `-Wconversions` helps keep track of types and forces one to think

Fix warnings

---

SparseGrids/tsgGridFourier.cpp

This branch adds explanatory comments for `exponent_refs` and `convertIndexes()`. Additionally, variable names in `convertIndexes()` were changed to clarify the algorithm; the computation is unchanged. I also changed the nebulous phrase "external indexing" to "spatial indexing."

Add explanatory comments

---

SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp

Implemented a cache for computing the exponential basis functions. Removed old routines for computing basis functions. Template `computeExponentials` includes a boolean flag to return the real and imaginary parts either interwoven or separately.

Add exponentials cache

---

SparseGrids/tsgGridFourier.hpp

* OpenMP directives rely on the pre-processor, templates are instantiated after the pre-processor
* will think about this in the future, but OpenMP will make little difference here

OpenMP does not work with templates

---

SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgIndexManipulator.cpp
SparseGrids/tsgIndexSets.cpp
SparseGrids/tsgIndexSets.hpp

* the `IndexSet` classes and the `StorageSet` are converted to use `size_t` and `std::vector`
* many of the internal merge functions use iterators
* the I/O file format remains uchainged
* many of the functions interfacing with the sets had to be updated

Convert indexing to size_t

---

docker/Dockerfile_nvidia-cuda9.0-ubuntu16.04
docker/Dockerfile_stack
docker/jenkins/build.sh

I already built the new images and uploaded them on Docker Hub.
This is safe to merge if the CI passes.

Enable Fortran in GCC builds on Jenkins CI

---

SparseGrids/tsgIndexSets.cpp

* technically a false positive as `p` is always initialized, but must be fixed

flagged by werror

---

InterfaceFortran/TasmanianSG.f90
InterfacePython/TasmanianSG.in.py
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp

This branch reformats the internal storage of `fourier_coefs`. Internally, the coefficients are arranged so that all real parts are in the first block, and all imaginary parts are in the second block. In CLI-write, `fourier_coefs` is written to a file in the usual interwoven format. MATLAB, Python, and CLI-print will report the coefficients to the user as complex numbers.
(There were no edits to the MATLAB files because they already assumed that CLI-write uses the interwoven format.)

Reformat Fourier coefficients

---

Config/CMakeLists.examples.txt

* C++ standard 2011 is now mandatory for Tasmanian
* C++11 directives are included in the headers (in templates)
* set the standard for the examples when they are compiled post-install

add cxx 11 standard for the examples (post install)

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCudaKernels.cu
SparseGrids/tsgCudaMacros.hpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgGridWavelet.hpp

* cuda errors now generate exceptions with meaningful messages
* old behaviour was using `logstream` or `os` streams to output messages in case of an error
* the streams are not needed any more and have been removed

Cuda exceptions

---

InterfacePython/testTSG.in.py
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgOneDimensionalWrapper.cpp
SparseGrids/tsgOneDimensionalWrapper.hpp

* replaced error messages in incorrect input with exception `std::invalid_argument(message)`
* replaced error messages in file I/O with exception `std::runtime_error(message)`
* respect backwards compatibility with file formats newer than version 3.0 (from 2015)
* cannot set domain transform for an empty grid
* it is now possible to create sequence grids with zero outputs (bad for performance, but mathematically valid)

Exceptions in file I/O

---

Makefile
SparseGrids/CMakeLists.txt
SparseGrids/Makefile
SparseGrids/gridtest_main.cpp
SparseGrids/tasgridUnitTests.cpp
SparseGrids/tasgridUnitTests.hpp
Testing/multiBuildTest.sh

* until now `tasgrid` was used for both testing and the CLI interface
* separate the tests into a second executable
* second executable runs in known location (cmake build folders), important for I/O tests
* reduces the size of the CLI interface executable
* right now, only one new test is included in very preliminary stage, more tests will come as this module grows

New tester executable

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridUnitTests.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgCoreOneDimensional.hpp

* each `make<type>Grid()` function has an overload that accepts vectors for level limits and anisotropy
* basic sanity check is performed to ensure that dimensions are positive, outputs are non-negative, the correct rule is used for the grid type, etc.
* exceptions are checked in the unit-test module

Vector and exceptions in make grids

---

SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgIndexSets.hpp

* removed the `[i * stride + j]` indexing in global grid get points and evaluate (no potential for overflow)

Overflow in global

---

SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp

Remove the possibility for integer overflow in sequence grids (so long as number of points, outputs, dimensions, and x remain within `int`, the product will not overflow)

Overflow sequence grids

---

SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridSequence.cpp

* reorder the for-loops for Global Grids, boosts performance when dealing with many outputs (and no blas or cuda)
* minor performance boost in evaluate local, removed overflow potential

Loop order

---

SparseGrids/tsgIndexSets.cpp

* MSVC++ requires that OpenMP loop indexing is signed
* clang restricts the for-loop test condition to simple comparison, no typecasting

fixed a clang bug with indexing

---

Config/AltBuildSystems/TasmanianSparseGrid.windows.hpp
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgHiddenExternals.hpp

* renamed the sparse/dense selection function for local polynomial grids (should have Acceleration in the name)
* updated the (deprecated) windows header with the change and fixed old bug (will remove the header right after the release)
* removed unused reference to double-complex BLAS, complex BLAS is no longer used

Sparse dense localp

---

SparseGrids/tsgCoreOneDimensional.cpp

* on Intel 18 compiler `((level == 0) ? 0 : (1 << level));` return 1 when `level == 0`
* same compiler `(level > 0) ? (1 << level) : 0;` returns the correct value

intel compiler has a strange bug, probably due to optimization

---

Config/AltBuildSystems/Makefile.in

* OSX g++ command links to clang which requires explicit c++11 flag
* fast-math flags make some tests fail due to rounding

Adjust flags for OSX compatibility

---

docker/Dockerfile_nvidia-cuda9.0-ubuntu16.04

Image with NVIDIA CUDA derives from Ubuntu 16.04 that comes with CMake 3.5 when
installing with the system package manager.  Instead here we now download binaries for CMake 3.10.
Note: I built and pushed to docker hub a `dalg24/tasmanian_stack:nvidia-cuda9.0-ubuntu16.04-18.10.0` image.  I already went ahead and tagged it as `dalg24/tasmanian_stack:nvidia-cuda9.0` so this is ready to merge after the CI checks pass.

Upgrade CMake in Docker image with CUDA

---

Config/AltBuildSystems/testTSG.py
InterfacePython/testTSG.in.py

* set the GaussPatterson.table file in only one location, makes it easier to keep in sync with GNU Make

fix the location of the GaussPatterson.table in the gnu make files

---

Doxygen/CMakeLists.txt
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.hpp
SparseGrids/tsgLinearSolvers.cpp
SparseGrids/tsgLinearSolvers.hpp
SparseGrids/tsgOneDimensionalWrapper.hpp

* fix the way internal documentation is skipped without `-D DOXYGEN_INTERNAL_DOCS=YES`
* document core one dimensional methods, one-d wrapper and linear solvers
* fix documentation for the multi-index templates

More internal docs

---

SparseGrids/CMakeLists.txt
SparseGrids/Makefile
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridExternalTests.hpp
SparseGrids/tsgDConstructGridGlobal.cpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.cpp

Implemented a dynamic construction procedure for global grids.
* construction must be explicitly initiated
* a new set of nodes can be requested at any time similar to get `getNeeded()` but the points will be ordered according in descending order in terms of contribution to the overall accuracy (according to anisotropic quasi-optimal estimate)
* the points can be given to Tasmanian in any arbitrary order and one point at a time, the grid will be updated on the fly
* a new updated and reordered list of points can be requested regardless whether the current set has been loaded or not
* the dynamic procedure does not interfere with evaluate
* construction must be explicitly finalized, at which point the grid works just as before

Dynamic construction global

---

InterfacePython/testRefinement.py
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgDConstructGridGlobal.cpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.cpp
SparseGrids/tsgIndexSets.hpp

Added dynamic construction for sequence grids:
* templated several functions from Global grids, avoid code repetition
* added the logic of including one node at a time and recomputing surpluses
* updated the logic to keep the sequence cache up to date
* established the virtual interface to common construction functions
* added tests in C++ and Python (more testing is needed)

Dyconst sequence

---

Config/CMakeLists.examples.txt
DREAM/CMakeLists.txt
SparseGrids/CMakeLists.txt

* C++11 standard is set in a new way in CMake post 3.8 (old way doesn't propagate transitively)

updating cxx standard to the new cmake way

---

Config/CMakeIncludes/sanity_check_and_xsdk.cmake
Doxygen/CMakeLists.txt
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridUnitTests.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp

* Found a way to template the CudaVector while still hiding the CUDA API calls and thus removing the need to transitively include the CUDA headers
* The transitive inclusion of the CUDA headers creates havoc with CMake "CUDA as a language"
* Documented the API updates and the remaining useful acceleration methods and classes
* Updated the tests and domain transforms to use the cleaner CudaVectors templates

More dependency cleanup

---

DREAM/Examples/example_dream.cpp
DREAM/Examples/example_dream_01.cpp
DREAM/Examples/example_dream_02.cpp
DREAM/Examples/example_dream_03.cpp
DREAM/Examples/example_dream_04.cpp
DREAM/TasmanianDREAM.hpp
DREAM/tsgDreamCorePDF.hpp
DREAM/tsgDreamCoreRandom.hpp
DREAM/tsgDreamEnumerates.hpp
DREAM/tsgDreamInternalBlas.hpp
DREAM/tsgDreamLikelihoodCore.hpp
DREAM/tsgDreamLikelyGaussian.hpp
DREAM/tsgDreamSample.hpp
DREAM/tsgDreamSampleGrid.hpp
DREAM/tsgDreamSamplePosterior.hpp
DREAM/tsgDreamSamplePosteriorGrid.hpp
DREAM/tsgDreamState.hpp
Doxygen/CMakeLists.txt
Doxygen/Installation.md
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCacheLagrange.hpp
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgEnumerates.hpp
SparseGrids/tsgHiddenExternals.hpp
SparseGrids/tsgIOHelpers.hpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.hpp
SparseGrids/tsgLinearSolvers.hpp

* reorganized the Doxygen documentation into Sparse Grid, DREAM and Examples master modules with numerous sub-modules
* fixed typos, Doxygen warnings, and added some clarifications

merge the dogygen groups into sub-groups and add numerous fixes

---

DREAM/TasmanianDREAM.hpp
DREAM/tsgDreamCorePDF.hpp
DREAM/tsgDreamCoreRandom.hpp
DREAM/tsgDreamEnumerates.hpp
DREAM/tsgDreamLikelyGaussian.hpp
DREAM/tsgDreamSample.hpp
DREAM/tsgDreamSampleGrid.hpp
DREAM/tsgDreamSamplePosterior.hpp
DREAM/tsgDreamSamplePosteriorGrid.hpp
DREAM/tsgDreamState.hpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCacheLagrange.hpp
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgEnumerates.hpp
SparseGrids/tsgIOHelpers.hpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.hpp
SparseGrids/tsgLinearSolvers.hpp
SparseGrids/tsgOneDimensionalWrapper.hpp
SparseGrids/tsgSequenceOptimizer.hpp

* having redundant header includes does little to the code, but Doxygen generates spaghetti dependence graphs that make the code look worse than it is
* removed the redundant dependence in sparse grids and dream headers

Reduce headers

---

Config/CMakeIncludes/FindTasmanianCudaMathLibs.cmake
InterfacePython/CMakeLists.txt

* convert all CMake booleans to ON/OFF so Python needs only to check if variable is ON
* if no other `find_package()` commands are used, then `include(FindPackageHandleStandardArgs)` is needed

Daily fixes

---

CHANGELOG.md
InterfaceFortran/tsgC2Fortran.cpp
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/TasmanianSparseGridWrapC.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridUnitTests.cpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tasgrid_main.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp

* broken backwards API for some funcitons
* Tasmanian C++ API no longer returns raw-pointers that need to be deleted
* proper C++ containers are returned instead, i.e., std::vector and std::string
* externally allocated raw-pointers are still accepted (used by the C/Python/Fortran APIs)
* mostly affects the points and weights, but also level limits and GPU name
* vectors can still be passed in by reference
* moved on-liner function from the .cpp file to the header (for blobbing reduction more than speed)
* the read/write commands operate on basic streams, this change is backwards compatible
* the C and Fortran interfaces still return raw-pointers as they did before (no change here)

Update container api

---

SparseGrids/tasgridExternalTests.cpp

Different compilers implement `std::forward_list::sort()` differently, despite the standard stating that it should be "stable sort". While the dynamic refinement algorithms do not require a stable-sort, differences in sorting result in different number of points, thus tests have to be more flexible. Instead of checking for the specific number of points, we now check for minimum acceptable error per number of nodes.

Sort independent dynamic test

---

SparseGrids/tsgDConstructGridGlobal.cpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridCore.cpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgIndexManipulator.cpp
SparseGrids/tsgIndexManipulator.hpp
SparseGrids/tsgIndexSets.cpp
SparseGrids/tsgIndexSets.hpp

* no functions move out of simple vector references, but use `&&` instead
* every call is now explicit move or copy (visible without referring to the api docs)
* using `emplace` instead of creating local variables and explicitly calling `push(move(foo))`

Improved move semantics

---

DREAM/dreamtest_main.cpp
SparseGrids/tasgridCLICommon.hpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgCoreOneDimensional.hpp
SparseGrids/tsgEnumerates.hpp

* converted dream cli tests to the dequeue mechanism and switched enum to string maps to std::map
* resulting in the removal of `strcmp()` usage and the need for `string.h` header

Remove stringh

---

CMakeLists.txt
Config/CMakeIncludes/exports.cmake
Config/CMakeIncludes/setup_message.cmake
Config/TasmanianMakefile.in
InterfacePython/CMakeLists.txt
Testing/test_post_install.in.sh

* split CMake configure exports and config message to separate files
* added export file for GNU Make build system that is using Tasmanian + CMake
* copy the Python version independent module under Windows (Linux uses sym-link)

Improved build system

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridExternalTests.hpp
SparseGrids/tasgridTestFunctions.cpp
SparseGrids/tasgridTestFunctions.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp

- start base functionality for `estimateAnisotropicCoefficients()` for Fourier grids
- highly similar to `tsgGridSequence.cpp` and `tsgGridGlobal.cpp`
- add tests for `estimateAnisotropicCoefficients` in Fourier case

begin anisotropic refinement for Fourier grids

---

SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgLinearSolvers.cpp
SparseGrids/tsgLinearSolvers.hpp

Switched tabs to spaces for consistency. Geany kept catching the tabs in `tasgridExternalTests.cpp`, so I did a find-replace job on all the files in `SparseGrids/`. Otherwise I have to go back in and manually re-add the tabs afterwards.

replace tabs with spaces for consistency

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/TasmanianSparseGridWrapC.cpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgOneDimensionalWrapper.cpp
SparseGrids/tsgOneDimensionalWrapper.hpp

* constructed points can now be loaded in batches of arbitrary order
* construction cost can now be amortized to O(n log(n)) as opposed to O(n^2)
* sequence and localp grids can be constructed from points and values only

Batch load constructed

---

Addons/CMakeLists.txt
docker/Dockerfile_stack
docker/jenkins/build.sh

* Makes sure that we add MPI to the docker image the next time we update the image. 
* MPI testing is enabled in the nightly builds, so actual updating can wait.

add mpi to the docker image

---

Addons/CMakeLists.txt
Addons/TasmanianAddons.hpp
Addons/testConstructSurrogate.hpp
Addons/tsgConstructSurrogate.hpp
Addons/tsgLoadNeededValues.hpp
Doxygen/CMakeLists.txt

* added simple template that loads model values statically (without refining the grid)
* the template uses a lambda-model and can run in parallel or sequential mode

Load values

---

Addons/testConstructSurrogate.hpp
Addons/testMPI.cpp
Addons/tsgCandidateManager.hpp
Addons/tsgConstructSurrogate.hpp
Addons/tsgMPIScatterGrid.hpp
InterfacePython/TasmanianSG.in.py
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridWrapper.cpp
SparseGrids/tsgCoreOneDimensional.cpp
SparseGrids/tsgDConstructGridGlobal.cpp
SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgGridWavelet.hpp
SparseGrids/tsgIOHelpers.hpp
SparseGrids/tsgIndexSets.cpp

* added constexpr constants for expressive calls to mode selection (parallel and io-mode)
* consistent naming for IO variables and templates when using binary and ascii modes
* adjusted the checkpointing strategy for the parallel surrogate construction

Small adjustments

---

Addons/CMakeLists.txt
Addons/testMPI.cpp
Addons/testMPI.hpp
Addons/testMPIDREAM.hpp
Addons/tsgMPIConstructGrid.hpp
Addons/tsgMPIScatterDREAM.hpp
Addons/tsgMPIScatterGrid.hpp
DREAM/tsgDreamLikelihoodCore.hpp
DREAM/tsgDreamLikelyGaussian.hpp
DREAM/tsgDreamSamplePosterior.hpp
Doxygen/CMakeLists.txt

* switched all MPI send/recv commands for objects to a single MPI API call
* added methods to send/recv/scatter a Bayesian likelihood across an MPI comm

Scatter likelihood

---

InterfaceFortran/Examples/example_sparse_grids.f90

* fixed mem leak in fortran examples

fixed fortran examples memory leak

---

Addons/CMakeLists.txt

* cmake puts the wrong .so extension for module libs under osx, switched the addon lib to shared

fixed osx python build issue

---

SparseGrids/tsgGridFourier.cpp

fix stability issues when evaluating the interpolation weights at a grid node with the O(N) algorithm

Stability issues with interpolation weights in Fourier grids

---

Config/AltBuildSystems/tasgridLogs.hpp
Config/CMakeIncludes/CMakeLists.txt
Config/CMakeIncludes/setup_message.cmake
InterfacePython/Tasmanian.py
InterfacePython/TasmanianConfig.in.py
Makefile
SparseGrids/tasgridLogs.in.hpp
SparseGrids/tasgrid_main.cpp

* `tasgrid -log` and `python -m Tasmanian` now dump the install log
* `tasgrid -cmakelog` now dumps a bunch of CMAKE parameters
* scikit deletes the temp build folder after install, this gives a fighting change to debug CMAKE issues when running pip-install

Display logs

---

docker/Dockerfile.doxygen

* the formulas also require `latex` and `ghostscript`, added to the docker

added texlive and ghostscript to doxygen

---

SparseGrids/CMakeLists.txt
SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridExternalTests.hpp
SparseGrids/tasgridTestHelpers.hpp
SparseGrids/tsgAcceleratedDataStructures.cpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgCudaBasisEvaluations.hpp
SparseGrids/tsgCudaKernels.cu
SparseGrids/tsgCudaLoadStructures.hpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.cpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgGridWavelet.hpp

The GPU direct calls to Tasmanian and the `evaluateBatch()` with cuda backend now accepts float vectors and arrays. The cached data-structures and the CUDA kernels work in single precision.

Mixed precision

---

.jenkins

Skip the tests when building the documentation right after merging a PR.

skip testing build when merging

---

CHANGELOG.md
Config/CMakeIncludes/CMakeLists.txt
Config/CMakeIncludes/all_examples.cmake
Config/CMakeIncludes/exports.cmake
Config/CMakeIncludes/master_targets.cmake
Config/CMakeLists.examples.txt
Config/TasmanianConfig.in.cmake
Doxygen/Installation.md

* split the Tasmanian::Tasmanian and the Tasmanian::Fortran into two targets
* updated the documentation to reflect the change

Cmake split fortran cxx

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp

* allow global surplus refinement to be done using the local method, ignores the extra inputs

surplus refinement can be called through one method

---

Addons/tsgLoadUnstructuredPoints.hpp
Config/CMakeIncludes/FindTasmanianMagma.cmake
Config/CMakeIncludes/sanity_check_and_xsdk.cmake
InterfaceTPL/tsgCudaWrappers.cpp
InterfaceTPL/tsgHipWrappers.cpp
InterfaceTPL/tsgHipWrappers.hpp
InterfaceTPL/tsgMagmaWrappers.hpp
SparseGrids/tsgAcceleratedDataStructures.hpp
SparseGrids/tsgLinearSolvers.cpp

* out-of-core MAGMA methods are now usable through the HIP backend with HIP-MAGMA
* enabled complex LQ factorization that was added in rocm 3.7

Enable hip magma

---

.jenkins

Docker Hub started enforcing rate limits and we started having issues on our Jenkins CI server
```
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Do not attempt to pull a newer version of images in Jenkins CI builds

---

InterfaceFortran/TasmanianSG.f90

* fix a call to the wrong function in fortran90

fix name of called function

---

Config/AltBuildSystems/tasgridLogs.hpp
SparseGrids/tasgridExternalTests.cpp
SparseGrids/tasgridExternalTests.hpp
SparseGrids/tasgridLogs.in.hpp
SparseGrids/tasgrid_main.cpp

* the Gauss-Patterson table can now be found in the installation folder
* tasgrid -test works post-install

gauss-patterson table can be found post-install

---

Doxygen/CMakeLists.txt
InterfaceTPL/tsgDpcppWrappers.cpp
InterfaceTPL/tsgDpcppWrappers.hpp

Allows for device selection logic similar to CUDA and HIP, but note that passing in a `sycl::queue` is still the preferred and most SYCL-ish way to select the device.

updated the sycl device selection logic

---

Config/CMakeIncludes/exports.cmake
Config/TasmanianConfig.in.cmake
InterfacePython/example_dream.in.py
InterfacePython/example_sparse_grids.in.py
Testing/CMakeLists.test.cmake
Testing/test_post_install.in.sh

* move the `test_install` testing into a CMake module for use post-install (previously it was a bash script)
* should facilitate better smoke testing in spack

added cmake post-install-testing

---

Addons/testAddons.cpp
Addons/testExoticQuadrature.hpp
Addons/tsgExoticQuadrature.hpp

This PR also includes some minor fixes in the testing code.

Allow `getExoticQuadrature()` to use `decompose()` instead of `LAPACK` + Bug fixes.

---

SparseGrids/gridtestExternalTests.cpp
SparseGrids/tsgCacheLagrange.hpp

**Note**:
- Branching has been removed by adding three additional if-statements and four additional for-loops.
- The tolerances in some global grid tests have also been adjusted.

Remove branching from the Lagrange derivative computation

---

SparseGrids/gridtestExternalTests.cpp
SparseGrids/tsgCacheLagrange.hpp
SparseGrids/tsgGridGlobal.cpp

This PR removes every if-statement inside the major for-loops used in `GridGlobal::getDifferentiationWeights()`. 
Note:
- The tolerances used in the grid tests have been slightly adjusted.
- The computation of the derivative cache in `CacheLagrangeDerivative::getLagrangeDerivative` now requires `O(num_points)` additional storage space instead of `O(1)` space as in the previous version. This is because we are not splitting the logic based on whether or not `x` is at a node.

Optimization of differentiation in global grids

---

DREAM/Optimization/tasdreamOptimizationTests.cpp
DREAM/Optimization/tsgParticleSwarm.hpp

Certain state vectors should be resized and reset when either `num_dimensions` or `num_particles` change.

Small bug fix to Particle Swarm API

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/gridtestExternalTests.cpp
SparseGrids/gridtestTestFunctions.cpp
SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridFourier.hpp

Bug fixes include:
- Corrections to derivatives defined in `gridtestTestFunctions.cpp`
- Including the effect of affine (non-conformal) domain transforms in `TasmanianSparseGrid::differentiate()`

Add differentiation to Fourier grids + small bug fixes

---

SparseGrids/Benchmarks/benchCommon.hpp
SparseGrids/Benchmarks/benchDifferentiate.hpp
SparseGrids/Benchmarks/bench_main.cpp
SparseGrids/CMakeLists.txt

* add a benchmark for the differentiation option, available for all grid types
* example usage: `./SparseGrids/benchmarksgrid differentiate wavelet 6 1 2 level wavelet 1 10 10`
* see also `./SparseGrids/benchmarksgrid differentiate help`

added differentiation benchmark

---

SparseGrids/TasmanianSparseGrid.cpp
SparseGrids/gridtestExternalTests.cpp
SparseGrids/tsgGridCore.hpp
SparseGrids/tsgGridFourier.hpp
SparseGrids/tsgGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgGridSequence.hpp
SparseGrids/tsgGridWavelet.hpp

- Add virtual functions to the base canonical grid class
- Remove excessive if statements from `gridExternalTests.cpp` and `TasmanianSparseGrid.cpp`

Simplify the differentiation code

---

DREAM/Optimization/TasmanianOptimizationWrapC.cpp
InterfacePython/CMakeLists.txt
InterfacePython/TasmanianGradientDescent.py
InterfacePython/testOptimization.py
InterfacePython/testTSG.py

This PR implements three changes:
- Adds Python unit tests for the `GradientDescent` functions
- Adds the optimization tests to the list of Python CTests 
- Adds a missing Python wrapper for the `setAdaptiveStepsize()` method in the `GradientDescentState` class

Add GradientDescent tests + small fixes

---

DREAM/Optimization/TasmanianOptimizationWrapC.cpp
DREAM/Optimization/tasdreamOptimizationTests.cpp
DREAM/Optimization/tsgParticleSwarm.cpp
DREAM/Optimization/tsgParticleSwarm.hpp
InterfacePython/TasmanianParticleSwarm.py
InterfacePython/testExceptions.py
InterfacePython/testOptimization.py

I would like to change the `ParticleSwarm` function signature to be more structured, like the `GradientDescent` function signature. Specifically, I would like to change its inputs to follow this ordering:
```
([optimization functions], [algorithm parameters], [iteration limits], [tolerance limits], [optimization state], [other]) 
```

Change ParticleSwarm function signature

---

SparseGrids/gridtestExternalTests.cpp

* disable some tests when `--fast-math` is enabled, note it is the default for `ipcx`

fix fast-math issue

---

CMakeLists.txt
Config/TasmanianConfig.in.hpp
Config/TasmanianMakefile.in
InterfaceSwig/FortranTests/fortranswigtester.f90

* small fixes for the build systems

Build system cleanup

---

SparseGrids/tsgGridFourier.cpp
SparseGrids/tsgGridGlobal.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridWavelet.cpp
SparseGrids/tsgIndexManipulator.hpp

Ambiguity in the C++ standard or in the way it is interpreted causes a bug in some of the newest compilers, e.g., clang 17 and msvc.
This is a workaround, in fact, this should not have been allowed in the first place, but it was easy to miss.

clang17 ambiguity in standard

---

SparseGrids/tsgEnumerates.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgHierarchyManipulator.cpp
SparseGrids/tsgHierarchyManipulator.hpp
SparseGrids/tsgRuleLocalPolynomial.hpp

* added global Kronecker method for computing the coefficients of a local polynomial grid

Fast localp coefficients recompute

---

CHANGELOG.md
CMakeLists.txt
Config/AltBuildSystems/TasmanianConfig.hpp
InterfacePython/TasmanianAddons.py
InterfacePython/TasmanianSG.py
Makefile
SparseGrids/tsgEnumerates.hpp

* cleaned deprecated support for python 2 and updated some docs and includes

Small fixes

---

SparseGrids/tsgGridLocalPolynomial.cpp

First of all, thanks for an excellent library. I use TASMANIAN on almost a daily basis for a combination of uncertainty quantification and surrogate dataset generation. 
When building larger surrogate datasets, I noticed runtimes grew rapidly compared to the number of points added during surplus refinement. For some of my faster running models, TASMANIAN was accounting for 99%+ of the runtime, and most of that was spent in `buildUpdateMap`. 
I profiled the code and noticed that the vast majority of the calculations were spent allocating `std::vector<int>`, which I tracked down to the allocation of `global_to_pnts` inside the parallel loop.  This PR significantly reduces the number of allocations by moving `global_to_pnts` outside of the parallel loop and allocating them for each thread …

Avoid excess allocations in buildUpdateMap

---

Addons/testLoadUnstructured.hpp
SparseGrids/gridtestExternalTests.cpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgHierarchyManipulator.hpp
SparseGrids/tsgIndexSets.hpp
SparseGrids/tsgSequenceOptimizer.cpp

* adding a few improvements to the refinement algorithm

Improve updatemap

---

InterfacePython/TasmanianAddons.py
InterfacePython/TasmanianDreamLikely.py
InterfacePython/TasmanianDreamSampler.py
InterfacePython/TasmanianDreamState.py
InterfacePython/TasmanianGradientDescent.py
InterfacePython/TasmanianSG.py
InterfacePython/testAcceleration.py

* enable apple silicon compatibility
closes #655

fix python library bugs

---

SparseGrids/tsgDConstructGridGlobal.hpp
SparseGrids/tsgGridLocalPolynomial.cpp
SparseGrids/tsgGridLocalPolynomial.hpp
SparseGrids/tsgHierarchyManipulator.cpp
SparseGrids/tsgHierarchyManipulator.hpp
SparseGrids/tsgRuleLocalPolynomial.hpp

Local polynomial rule is now based on templated and static polymorphism (as opposed to runtime).

templates for local polynomial rules

---

.github/workflows/build-ubuntu.yaml
.jenkins
CMakeLists.txt
InterfacePython/CMakeLists.txt
InterfacePython/testTSG.py
Tasgrid/tasgridLogs.in.hpp

Fix usage of the deprecated `PYTHON_EXECUTABLE`

fix python executable usage

---

Doxygen/Installation.md

Update the installation instruction for the install

update the documentation

---

SparseGrids/CMakeLists.txt
SparseGrids/TasmanianSparseGrid.hpp
SparseGrids/tsgAcceleratedDataStructures.hpp

c++-20 compatibility
